// Generated from sat-cmp-2025-c3-int-05-module-1.json, sat-cmp-2025-c3-int-05-module-2.json
// Review answers and images before publishing.

import type { MockTestSet } from '../mockTestQuestions'

export const importedMockTest = {
  "id": "sat-cmp-2025-c3-int-05",
  "title": "SAT CMP 2025-C3-INT-05",
  "year": 2025,
  "modules": [
    {
      "name": "Module 1 (Routing)",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "Cognitive science research has found that people tend to be biased against art when they think it was generated by artificial intelligence (AI) software. One hypothesis for the preference for human-created art is that people ____ the effort behind a piece of art: the more work they believe went into a piece's creation, the more likely they are to appreciate it.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "value",
            "perform",
            "prevent",
            "neglect"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 2,
          "passage": "The presence of Belarus's Mir Castle Complex on the United Nations Educational, Scientific, and Cultural Organization's World Heritage List indicates that the organization has _____ the site's \"outstanding universal value,\" and that UNESCO is therefore championing its preservation and protection.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "exploited",
            "recognized",
            "impeded",
            "neglected"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 3,
          "passage": "During film's early years, those who worked in the industry had a vested interest in convincing the public to embrace the new medium. As Sumiko Higashi argues, some filmmakers relied on film critics to influence the public's _____ the world of cinema. Critics who drew similarities between film and traditional art forms, like drama, could help legitimize film as an art form.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "contribution to",
            "perception of",
            "reproduction of",
            "application to"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "The following text is from Amy Tan's 1989 novel The Joy Luck Club. The narrator describes practicing the piano when she was a child. For the talent show, I was to play a piece called \"Pleading Child\" from Schumann's Scenes from Childhood. It was a simple, moody piece that sounded more difficult than it was. I was supposed to memorize the whole thing, playing the repeat parts twice to make the piece sound longer. But I dawdled over it, playing a few bars and then cheating, looking up to see what notes followed. I never really listened to what I was playing. I daydreamed about being somewhere else, about being someone else. ©1989 by Amy Tan",
          "question": "Based on the text, when the narrator describes herself as \"cheating,\" what does she most likely mean?",
          "options": [
            "she was lying to herself about her musical ability.",
            "She was violating an expectation about how to perform the piece.",
            "She was deceiving her piano teacher.",
            "She was gaining an unfair advantage over other contestants in the talent show."
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "The following text is adapted from George Eliot's 1857 short story \"The Sad Fortunes of the Rev. Amos Barton.\" Mr. Ely is a clergyman in the town of Milby. By the laity of Milby and its neighbourhood [Mr. Ely] was regarded as a man of quite remarkable powers and learning, who must make a considerable sensation in London pulpits and drawing-rooms on his occasional visit to the metropolis; and by his brother clergy he was regarded as a discreet and agreeable fellow. Mr. Ely never got into a warm discussion; he suggested what might be thought, but rarely said what he thought himself; he never let either men or women see that he was laughing at them, and he never gave any one an opportunity of laughing at him.",
          "question": "Which choice best describes the overall structure of the text?",
          "options": [
            "It details how Mr. Ely initially won his colleagues' admiration and then reports on the circumstances that prompted them to revise their views of him.",
            "It implies that Mr. Ely's neighbors are more naive in their estimation of him than people in London are and then explains why his neighbors have been so easily misled.",
            "It illuminates how Mr. Ely conducts himself differently in public and in private and then touches on why he is cautious to reveal some aspects of his character to other people.",
            "It presents the favorable opinion of Mr. Ely that other people hold and then describes the behaviors of Mr. Ely that enable him to maintain that favorable opinion."
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 6,
          "passage": "Text 1 Chemically analyzing bulk rock-core samples from Australia's Mount McRae Shale, Ariel Anbar et al. found a transient but significant increase in molybdenum (Mo) at a point corresponding to roughly 2.5 billion years ago (Ga). On Earth, Mo is released mainly through oxidative weathering of minerals; Anbar et al. therefore concluded that atmospheric oxygen briefly increased 2.5 Ga, then returned to its earlier negligible level. Text 2 Sarah Slotznick et al. reexamined the Mount McRae Shale core. Since chemically analyzing bulk samples can occlude contextual details, Slotznick et al. also employed high-resolution microscopy, which revealed volcanic debris—a known Mo host—around 2.5 Ga and microfractures in the surrounding matrix. The researchers assert that fluid could have reached the debris through the microfractures and initiated oxidative weathering long after debris deposition.",
          "question": "Based on the texts, Anbar et al. (Text 1) and Slotznick et al. (Text 2) would most likely disagree about the answer to which question about the portion of the Mount McRae Shale rock-core corresponding to 2.5 Ga?",
          "options": [
            "Is the increase in Mo in that portion attributable to oxidative weathering of the material found in that portion?",
            "Is the increase in Mo in that portion indicative of an increase in atmospheric oxygen dating to the same time?",
            "Did chemically analyzing bulk samples lead to a false impression that there is an increase in Mo in that portion?",
            "Does the increase in Mo in that portion suggest that atmospheric oxygen levels were not negligible before 2.5 Ga?"
          ],
          "answer": 1
        },
        {
          "id": 7,
          "passage": "Many artists associated with hyperpop, a movement in electronic music that emerged in the 2010s, conform to the model perfected by the American duo 100 gecs: bold synthesizer arrangements, propulsive beats, and electronically manipulated vocals. Yet the movement is hardly uniform: British recording artist Charli XCX incorporates pop melodies into the hyperpop sound, for example. Such stylistic diversity is encouraged in part by the music-streaming app Spotify, whose curated playlist of hyperpop songs balances cohesion with variety.",
          "question": "Which statement about Charli XCX is best supported by the text?",
          "options": [
            "Her inclusion on Spotify's hyperpop playlist inspired established artists to embrace stylistic experimentation.",
            "She developed her unique sound without being influenced by other artists on Spotify's hyperpop playlist.",
            "While some of her recordings conform to the model perfected by 100 gecs, others reject it outright.",
            "Her music diverges from the typical hyperpop sound but doesn't abandon it."
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 8,
          "passage": "In a study by Mika R. Moran, Daniel A. Rodriguez, and colleagues, residents of Quito, Ecuador, and Buenos Aires, Argentina, were surveyed about parks in their cities. Of the 618 respondents from Quito, 82.9% indicated that they use the city's parks, and of the 683 respondents from Buenos Aires, 69.9% indicated using city parks. Given that the percentage of Quito respondents who reported having access to other desired amenities near parks was much lower than that reported by Buenos Aires respondents, the difference in park use can't be explained by Quito residents having more access to desired nonpark amenities near parks.",
          "question": "Which choice best describes the main idea of the text?",
          "options": [
            "The study's finding that a greater proportion of residents use parks in Quito than in Buenos Aires is partly due to the greater prevalence of parks in Quito.",
            "The study's findings suggest that an increase in the number of amenities near city parks would likely increase park use in Quito but not in Buenos Aires.",
            "Although the study found that a greater proportion of residents use parks in Quito than in Buenos Aires, that difference isn't due to greater access to amenities near parks in Quito.",
            "Even though the study found that parks in Buenos Aires are more likely to be close to other amenities than parks in Quito are, Quito has more amenities overall than Buenos Aires does."
          ],
          "answer": 2
        },
        {
          "id": 9,
          "passage": "Lin-Tai Ho and colleagues monitored fish populations in a tide pool in Taiwan. They found that some species were entirely absent from the tide pool at particular times of the year; for example, they did not observe even one ________",
          "question": "Which choice most effectively uses data from the graph to complete the example?",
          "options": [
            "wavy-lined blenny in January, April, and July of 2001.",
            "Indo-Pacific sergeant in October of 2001.",
            "Indo-Pacific sergeant in July of 2001.",
            "Cocos frillgoby in April of 2001."
          ],
          "answer": 0,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "image": "/sat-cmp-2025-c3-int-05-m1-q9.svg"
        },
        {
          "id": 10,
          "passage": "\"The Monster\" is an 1898 story by Stephen Crane. In the story, whenever Jimmie, a young boy, has been scolded by his father for misbehavior, he seeks comfort from Henry Johnson, the man responsible for the care of Jimmie's father's horses. However, Henry does not always provide such comfort; Crane suggests this by writing, _______",
          "question": "Which quotation from \"The Monster\" most effectively illustrates the claim?",
          "options": [
            "\"For one thing, Jimmie was invariably overcome with reverence when he was told how beautifully a harness was polished or a horse groomed.\"",
            "\"Henry... could usually provide a sin to place himself on a footing with the disgraced one. Perhaps he would remember that he had forgotten to put the hitching-strap in the back of the buggy on some recent occasion, and had been reprimanded by [Jimmie's father].\"",
            "\"Henry would sometimes choose to absolutely repudiate [Jimmie's behavior], and when Jimmie appeared in his shame would bully him most virtuously, preaching with assurance the precepts of [Jimmie's father's] creed, and pointing out to Jimmie all of his abominations.\"",
            "\"Whenever Henry dwelt for a time in sackcloth [a symbol of guilt over wrongdoing], Jimmie did not patronize him at all.\""
          ],
          "answer": 2
        },
        {
          "id": 11,
          "passage": "To measure whether countries in free trade agreements (FTAs)—agreements among nations to reduce tariffs, duties, and other trade barriers—experience changes in total agricultural exports, economist Kayode Ajewole and colleagues calculated average export growth rates for several countries over the five years before and the five years after entering an FTA with the United States. The graph shows the results for three countries in the study. Consulting the graph, a student claims that joining an FTA increases the rate of growth of a country's total agricultural exports.",
          "question": "Which choice best describes data from the graph that weaken the student's claim?",
          "options": [
            "Although agricultural exports from Mexico decreased over the five years before NAFTA, a reversal in this trend was observed over the five years after Mexico joined NAFTA.",
            "Although agricultural exports from Nicaragua grew over the five years after Nicaragua joined CAFTA-DR, their growth rate was even higher in the five years before CAFTA-DR.",
            "Over the five years after EI Salvador joined CAFTA-DR, agricultural exports from El Salvador grew at a rate of about 21.8 percent, which is higher than the rate over the five years before EI Salvador joined the agreement.",
            "All the countries shown had positive growth in agricultural exports over the five years after joining their respective FTAS, but their rates of export growth varied."
          ],
          "answer": 1,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "image": "/sat-cmp-2025-c3-int-05-m1-q11.svg"
        },
        {
          "id": 12,
          "passage": "Michelle Pereira et al. hypothesized that introducing health improvements into workplaces would increase productivity by reducing absenteeism (sick employees not working) and presenteeism (sick workers working less productively due to illness). Pereira's team enrolled groups of Australian workers in two programs; one that gave employees exercise training (EET) and one that enrolled employees in health promotion seminars (EHP). They then calculated the productivity loss of those groups at 12 weeks and 12 months after the programs began (based on the 28 days preceding each point). They concluded that exercise training was more effective at restraining productivity loss than health promotion seminars were, though this result took time to become apparent.",
          "question": "Which choice best describes data from the table that most effectively strengthen Pereira and colleagues' conclusion?",
          "options": [
            "Productivity loss for the EET group barely decreased between 12 weeks and 12 months after the program began, while productivity loss for the EHP group significantly increased during the same time period.",
            "Productivity loss was largely due to absenteeism for the EHP group at 12 months after the program began, while productivity loss was largely due to presenteeism for the EET group at 12 months after the program began.",
            "Productivity loss was consistently higher for the EHP group than for the EET group over the twelve months that it was measured, though the size of the difference between the two decreased over that time.",
            "Productivity loss was fairly similar for the EET and EHP groups 12 weeks after each program began, but at 12 months afterward it had significantly increased for the EHP group and significantly decreased for the EET group."
          ],
          "answer": 3,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Average Monetized Productivity Loss at Two Points After Programs Began, in Australian Dollars",
            "headers": [
              "Type of training",
              "12 weeks",
              "12 months"
            ],
            "rows": [
              [
                "EET",
                "268",
                "171"
              ],
              [
                "EHP",
                "282",
                "436"
              ]
            ]
          }
        },
        {
          "id": 13,
          "passage": "Water flowing around an obstruction creates vortices (patterns of swirls) of varying size; by detecting the vortices, fish can determine the size and position of the obstruction. Testing by Yuzo R. Yanagisuru, Otar Akanyeti, and James C. Liao using models of three head shapes—narrow (low ratio of width to length), intermediate, and wide (high ratio of width to length)—showed that for medium-sized vortices, fish with wide heads would be least able to distinguish between vortices and general turbulence in the water. A second research team has therefore hypothesized that in low-visibility conditions, wider-headed fish will be less likely than narrower-headed fish to detect obstructions.",
          "question": "Which finding, if true, would most directly support the second research team's hypothesis?",
          "options": [
            "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the anglerfish (Lophiodes monodi), which has a relatively wide head, bumped into more than half of the obstructions.",
            "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the narrower-headed dusky smooth-hound (Mustelus canis) bumped into the obstructions just as often as the wider-headed anglerfish (Lophiodes monodi) did.",
            "A study using obstructions that created medium-sized vortices in low-visibility conditions found that the wider-headed anglerfish (Lophiodes monodi) bumped into obstructions more often than the narrower-headed dusky smooth-hound (Mustelus canis) did.",
            "A study using obstructions that created medium-sized vortices in low-visibility conditions found that some specimens of dusky smooth-hound (Mustelus canis), which has a relatively narrow head, bumped into the obstructions more often than other specimens of the same fish did."
          ],
          "answer": 2
        },
        {
          "id": 14,
          "passage": "J.G. Ballard's 1984 novel Empire of the Sun is regularly described as autobiographical. That characterization is apt—there are many parallels between the experiences of the novel's protagonist, Jim Graham, and those of Ballard—but it should not be taken to mean that every person or event depicted in Empire of the Sun has a real-life analogue. Much of the novel is pure invention, and readers who neglect this fact and instead focus excessively on correspondences between the novel and Ballard's life can thus _______",
          "question": "Which choice most logically completes the text?",
          "options": [
            "misrepresent Empire of the Sun as being more widely read than it actually is.",
            "overemphasize the extent to which Ballard took inspiration from earlier writers.",
            "fail to appreciate how much creativity Ballard shows in the book.",
            "refuse to acknowledge that Ballard drew on real-world material when writing Empire of the Sun."
          ],
          "answer": 2
        },
        {
          "id": 15,
          "passage": "The words \"utopia\" and \"nerd\" both trace _____ origins to books. \"Utopia\" first appears in Utopia by Sir Thomas More, and \"nerd\" first appears in If I Ran the Zoo by Dr. Seuss.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "there",
            "it's",
            "their",
            "they're"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 16,
          "passage": "With an average summer temperature of 61 degrees Fahrenheit, Moscow is one European ____ many travelers recommend, especially from June to September.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "city, that",
            "city, which",
            "city in which,",
            "city that"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 17,
          "passage": "Epic poetry is a literary genre characterized by lengthy narratives that emphasize the heroic or divine. The Argonautica, an epic poem of Greek origin, dates back to the ________ the poem's heroic narrative still captivates modern readers.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "3rd century BCE,",
            "3rd century BCE yet,",
            "3rd century BCE, yet",
            "3rd century BCE"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 18,
          "passage": "An upcoming exhibition will showcase Vincent van Gogh's drawing The Spire of the Church of Our Lady, which Van Gogh _____ in the city of Nuenen nearly 150 years ago.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "will complete",
            "has been completing",
            "completed",
            "is completing"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 19,
          "passage": "In addition to being a celebrated writer, musician, and educator, Zitkála-Šá (Yankton Dakota) was the cofounder of the National Council of American _____ advocated for Native American civil rights throughout the 1920s and 1930s.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "Indians. Which",
            "Indians,",
            "Indians",
            "Indians, which"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 20,
          "passage": "Cy Twombly, a US painter and sculptor, created many large-scale abstract works, such as his 10-painting series Fifty Days at Iliam. In these works, Twombly's artistic style is exemplified by his use of graffiti-like ____ often incorporate words or phrases from poetry and mythology.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "scribbles that",
            "scribbles: that",
            "scribbles; that",
            "scribbles. That"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 21,
          "passage": "For the past 20 million years, Earth's magnetic poles in the far north and far south have remained roughly where they are today. This has not always been the ____ throughout geologic history, Earth's magnetic poles have swapped places several times through a process called polar wandering.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "case, though,",
            "case, though;",
            "case; though,",
            "case, though"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 22,
          "passage": "In Ethiopia, citizens must be at least 18 years old to vote in their country's elections. _____ citizens in Cuba need only be 16 years old to cast their vote.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "By contrast,",
            "Firstly,",
            "For example,",
            "Therefore,"
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 23,
          "passage": "In astrophysics, a ring of debris orbiting a larger object within the object's Roche limit is expected to persist as a ring, whereas a ring of debris orbiting outside this limit would likely accrete into a satellite (e.g., a moon). Bruno Morgado and colleagues, _____ detected a dense ring of material orbiting the trans-Neptunian object Quaoar at a distance of 2,500 miles, well outside the calculated Roche limit of 1,100 miles, that has remained intact.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "for example,",
            "likewise,",
            "fittingly,",
            "though,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 24,
          "passage": "While researching a topic, a student has taken the following notes: • Dinosaur fossil specimens can be found at science museums all over the world. • Many dinosaur fossil specimens are given nicknames. • The Burke Museum of Natural History and Culture in Seattle, Washington, houses a dinosaur fossil specimen nicknamed Tufts-Love. • Tufts-Love lived in the Late Cretaceous period, which ended more than 65 million years ago. • It is a member of the genus Tyrannosaurus.",
          "question": "The student wants to provide an example of a dinosaur fossil specimen's nickname. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Dinosaur fossil specimens can be found at museums all over the world, and many of these specimens are given nicknames.",
            "Nicknames are given to many dinosaur fossil specimens, including one housed at a museum in Seattle, Washington.",
            "Tufts-Love is the nickname of a Tyrannosaurus fossil specimen housed at the Burke Museum of Natural History and Culture in Seattle, Washington.",
            "A Tyrannosaurus fossil specimen from the Late Cretaceous period, which ended more than 65 million years ago, is housed at the Burke Museum of Natural History and Culture."
          ],
          "answer": 2,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 25,
          "passage": "While researching a topic, a student has taken the following notes: • The Arabic word \"dinar\" comes from the Latin word \"denarius.\" • Today, nearly a dozen different national currencies are referred to as \"dinars.\" • Bahrain's currency is known as the Bahraini dinar.",
          "question": "The student wants to provide an example of a country that uses the word \"dinar\" in the name of its currency. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Bahrain uses the Bahraini dinar as its national currency.",
            "Bahrain does not refer to its currency by the Latin word \"denarius.\"",
            "Today, several countries use the word \"dinar\" in naming their currencies.",
            "The Latin word \"denarius\" is the origin of the Arabic word \"dinar.\""
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 26,
          "passage": "While researching a topic, a student has taken the following notes: • Most of the plant and bird species in Oahu, Hawaii, are non-native. • In a 2019 study, researchers wanted to know what role non-native birds play in dispersing plant seeds in Oahu. • Researchers catalogued plant seeds found in fecal samples from non native birds. • Leptecophylla tomeiameiae, a flowering shrub, was one of fifteen native species catalogued. • Passiflora suberosa, an herbaceous vine, was one of twenty-nine non-native species catalogued. • Researchers concluded that non-native birds play a vital role in dispersing the seeds of native and non-native plants.",
          "question": "The student wants to emphasize a difference between the two plants. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Most plant species found in Oahu, Hawaii, like Passiflora suberosa, are non-native.",
            "Seeds from Leptecophylla tameiameiae and Passiflora suberosa plants were found in the fecal samples of non-native Hawaiian birds, according to a 2019 study.",
            "A 2019 study catalogued plant seeds found in bird fecal samples in Oahu, Hawaii, to determine what role non-native birds play in seed dispersal.",
            "Though Leptecophylla tomeiameiae and Passifiora suberosa can both be found in Oahu, Hawaii, only the former plant is native."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes: • Generally, an object will heat up when twisted. • The twisting of an object is known as torsion. • A 2019 study led by Zunfeng Liu and Ray Baughman tested the torsional heating of various fibers. • When a sample of ethylene propylene diene monomer (EPDM) rubber fiber was twisted, its average surface temperature increased by 12℃. • When a sample of natural rubber fiber was twisted, its average surface temperature increased by 15.3℃.",
          "question": "The student wants to emphasize a similarity between EPDM rubber and natural rubber fibers. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "In 2019, two research teams observed the effects of torsional heating on various fibers, including EPDM rubber and natural rubber.",
            "Twisting an object will generally cause its temperature to increase, a process known as torsional heating.",
            "Researchers determined that when the fibers were twisted, the average surface temperature of natural rubber increased more than that of EPDM rubber.",
            "Both EPDM rubber and natural rubber fibers heat up when twisted, according to a 2019 study."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    },
    {
      "name": "Module 2 (27道题)",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "In some of his sculptures, Allan Houser uses abstract geometric shapes to depict his subjects rather than portraying them in realistic detail. For instance, his 1989 work Embrace is highly abstract and therefore differs strikingly from some of his other pieces in which the viewer can easily _____ familiar objects.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "ignore",
            "identify",
            "reveal",
            "remember"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 2,
          "passage": "Agglomeration economies arise when multiple firms in related industries ____ an area, as with knitted fabrics manufacturers and knitted clothing manufacturers in Derby, UK. Economists have assumed that companies cluster for the same reasons, but Giulia Faggio et al, found that factors driving agglomeration in some cases are only weakly correlated with agglomeration in others.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "intercede in",
            "amass in",
            "concur with",
            "appeal to"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 3,
          "passage": "The familial structure of the black swan (Cygnus atratus) shows tremendous _____: breeding pairs with demonstrated success in rearing cygnets (young swans) have been observed to foster those of less successful pairs, and while rearing by female-male pairs is most common, male-male pairs sometimes rear cygnets too, achieving a significantly higher rate of survival to adulthood than female-male pairs.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "elasticity",
            "reciprocity",
            "cohesion",
            "affection"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "Any effort to raise the toll that drivers must pay to use the Ogdensburg-Prescott Bridge, which spans the Saint Lawrence River to connect New York State and Ontario, Canada, should explain why a higher toll is necessary; no amount of justification, however, is likely to persuade some drivers who believe the current toll is ______.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "contentious",
            "exorbitant",
            "warranted",
            "equivocal"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "During the 2007-2010 financial crisis, the United States furnished billions of dollars to selected countries' central banks via mechanisms called swap lines. Aditi Sahasrabuddhe found that countries' policy environments seem to have been ____ swap-line decisions: the probability that banks would be granted swap lines was 0.20 in countries open to foreign-capital inflows and 0.03 in countries with policies restricting such inflows.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "predicated on",
            "decoupled from",
            "material to",
            "mediated by"
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 6,
          "passage": "Founded in New York City in 1969, El Museo del Barrio is dedicated to the visual arts and cultures of Latin America and of Latino communities in the United States. Since its founding, it has acquired more than 8,500 objects for its permanent collection. More recently founded US-based institutions devoted to Latino cultures include the Emma S. Barrientos Mexican American Cultural Center. Located in Austin, Texas, it focuses on Mexican American art and culture.",
          "question": "Which choice best states the main purpose of the text?",
          "options": [
            "To trace the founding of two institutions, including how they acquired funding to purchase artworks",
            "To trace a historical development that encouraged the founding of two institutions",
            "To present information about two institutions, including each institution's area of focus",
            "To draw a contrast between the collection sizes of two institutions"
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 7,
          "passage": "In 2011 Stephen D. Simpson and colleagues published a study concluding that ocean acidification has a strong effect on the behavior of Amphiprion percula, a species of fish. However, Simpson and colleagues' study relied on a mean sample size of only about 26 fish. In a 2022 review of various scientists' conclusions about the impacts of ocean acidification on fish behavior, Timothy D. Clark and colleagues caution that relying on such a relatively small sample size can increase the potential for biased analysis. Such analysis, in turn, can contribute to reports of exaggerated effects.",
          "question": "Which choice best describes the function of the underlined sentence in the text?",
          "options": [
            "It states the conclusion reached by Simpson and colleagues in their 2011 study.",
            "It presents a criticism of the results reported by Simpson and colleagues in their 2011 study.",
            "It lists several traits of Amphiprion percula discovered by Simpson and colleagues while conducting their 2011 study.",
            "It emphasizes a detail about where Simpson and colleagues conducted their 2011 study."
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 8,
          "passage": "Paintings by the Florida Highwaymen—an informal collective of prolific landscape artists active in Florida during the 1950s and '60s—are recognizable by their reiteration of the same general compositional structures and subjects: moonlit waters and poinciana trees, to name two. But there was room for individuation: Lemuel Newton's Salmon sky Sunset, for example, may resemble other Highwaymen paintings at first glance, but his works stand out for their attention to detail and warm color palette.",
          "question": "Which choice best describes the overall structure of the text?",
          "options": [
            "It describes the common perception that a particular group of artists' works are derivative and then provides a specific piece of evidence that reinforces that perception.",
            "It explains how a particular group of artists began collaborating and then recounts how one member of that group became especially influential among them.",
            "It describes an aesthetic framework shared by a particular group of artists and then makes and illustrates the claim that individuals introduced variations within that framework.",
            "It offers historical context that accounts for a particular group of artists' shared style and then indicates the circumstances under which several members of that group began exploring more unconventional themes."
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 9,
          "passage": "The following text is from Mick Herron's 2023 novel The Secret Hours. The narrator is describing members of a government committee. Finally, and adding much-needed gravitas, was Sir Winston Day, whose features seemed moulded to adorn a bust, or possibly a stamp, and whose forehead was so evidently bulging with grey matter that it would have been impertinent to inquire too closely into the actual achievements his half century of public service had produced. His recently published memoirs possibly cast light on this enigma, but given that such details were not provided until after the thirty-page mark, they might as well have remained state secrets. ©2023 by Mick Herron",
          "question": "Based on the text, which choice best describes Sir Winston Day?",
          "options": [
            "He has maintained a modest profile even though he has served the public capably for many years.",
            "He has the appearance of a distinguished figure, but it is uncertain whether he has accomplished anything to earn distinction.",
            "He looks like a person worthy of respect, but his memoirs reveal that some of his actions were dishonorable.",
            "He would be a celebrated public figure if his achievements did not have to be kept secret."
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 10,
          "passage": "Life Among the Paiutes is an 1882 autobiographical narrative by Sarah Winnemucca Hopkins, a Northern Paiute author, educator, and activist. In the work, Winnemucca directly addresses the reader to explain certain customs, writing ____",
          "question": "Which quotation from Life Among the Paiutes most effectively illustrates the claim?",
          "options": [
            "\"Now, my dear reader, there is no word so endearing as the word father, and that is why [my people] call all good people father or mother.\"",
            "\"We would all go in company to see if the flowers we were named for were yet in bloom, for almost all the girls are named for flowers.\"",
            "\"During the time my grandfather was away in California, where he [stayed] till after the Mexican war, there was a girl-baby born in our family.\"",
            "\"But how can I describe the scene that followed? Some of you, dear readers, can imagine.\""
          ],
          "answer": 0
        },
        {
          "id": 11,
          "passage": "Some scientists have suggested that as ocean temperatures rise, many fish and corals found in the shallow zone (less than 30 meters below the surface) could take refuge in the cooler, darker mesophotic zone (30 to 150 meters below the surface). However, it isn't clear that all such species will be able to tolerate mesophotic conditions. In 2018, Luiz Rocha and colleagues studied stony corals in the two zones in Caribbean and Indo-Pacific waters. Based on the depths at which those corals are now found, the species that seems least suited to a full migration to the mesophotic zone is ______",
          "question": "Which choice most effectively uses data from the table to complete the statement?",
          "options": [
            "Agaricia grahamae, because its minimum depth of 20 meters is in the shallow zone.",
            "Psammocora albopicta, because its minimum depth of 1 meter is the shallowest of those listed.",
            "Astreopora gracilis, because its maximum depth of 15 meters is furthest from the mesophotic zone.",
            "Acropora echinata, because its maximum depth of 25 meters is close to but doesn't reach the mesophotic zone."
          ],
          "answer": 2,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Minimum and Maximum Depths of Stony Coral Species in Caribbean and Indo-Pacific Waters",
            "headers": [
              "Species",
              "Minimum depth (meters)",
              "Maximum depth (meters)"
            ],
            "rows": [
              [
                "Psammocora albopicta",
                "1",
                "28"
              ],
              [
                "Agaricia grahamae",
                "20",
                "115"
              ],
              [
                "Astreopora gracilis",
                "5",
                "15"
              ],
              [
                "Acropora echinata",
                "8",
                "25"
              ]
            ]
          }
        },
        {
          "id": 12,
          "passage": "Although Eastern North Pacific (ENP) gray whales generally migrate between their wintering waters along the coast of Mexico and their foraging waters in the Arctic, a subset of this population—known as the Pacific Coast Feeding Group (PCFG)—forages along the coastlines of Northern California (USA) and British Columbia (Canada) instead. Interestingly, individuals in this subset reach smaller maximum sizes than other ENP whales do, despite having similar pre-maximum growth rates. Researchers hypothesize that this difference may be an adaptation to distinct resource opportunities in the PCFG foraging range.",
          "question": "Which finding, if true, would most directly support the researchers' claim regarding the size of PCFG whales?",
          "options": [
            "When foraging along the coasts of Northern California and British Columbia, PCFG whales are in closer proximity to major ports and urban populations than ENP whales in the main group are when foraging in Arctic waters.",
            "When present along the coasts of Northern California and British Columbia, PCFG whales tend to forage in rocky kelp beds at shallow depths inaccessible to whales as large as those in the ENP main group.",
            "Certain crustacean prey species available along the coasts of Northern California and British Columbia where PCFG whales tend to forage are not available in the Arctic waters where ENP whales in the main group forage.",
            "The average body size of PCFG whales observed along the coasts of Northern California and British Columbia has remained relatively steady in recent decades, while the average body size of ENP whales in the main group has slightly decreased."
          ],
          "answer": 1
        },
        {
          "id": 13,
          "passage": "Piezoelectric harvesters convert kinetic energy (resonance) to electrical energy, precluding the need for external electrical sources. The vibration of a spacecraft, for example, can provide sufficient energy to power many of its sensors piezoelectrically. A newly designed piezoelectric harvester incorporating a highly conductive carbon-fiber-reinforced polymer (CFRP) electrode has been shown to provide steady energy loads during resonance, an absolute prerequisite for wireless communication devices to be powered piezoelectrically.",
          "question": "Which finding, if true, would most directly support the text's claim about wireless communication devices?",
          "options": [
            "The near-constant kinetic vibration of a spacecraft makes it possible to power its wireless communication devices using only non-CFRP piezoelectric harvesters.",
            "The CFRP electrode is incompatible with most wireless communication devices.",
            "Intermittent or unpredictable electrical supply undermines the efficacy of wireless communication devices.",
            "The high conductivity of the CFRP is what makes the energy output from a piezoelectric harvester sufficient for wireless communication devices."
          ],
          "answer": 2
        },
        {
          "id": 14,
          "passage": "Consumers increasingly expect that goods they purchase online will be delivered rapidly, even as soon as the day of purchase. Although efficiencies in long-distance transport of parcels have greatly improved delivery times, last-mile logistics (the final step in delivery to consumers) present a bottleneck for delivery companies. Time pressure resulting from consumer expectations is not the only challenge; other obstacles, such as the increasing congestion of roadways, persist. While innovations to mitigate these challenges have been emerging—the use of cargo bikes, for instance—success has been constrained due to the additional complications that arise (e.g. the low parcel carrying capacity of the bikes). Consequently, _____",
          "question": "Which choice most logically completes the text?",
          "options": [
            "the use of cargo bikes may enable delivery companies to meet consumers' expectations now but likely is not viable as a permanent solution.",
            "in the near term, delivery companies are unlikely to overcome the impediments associated with last-mile logistics.",
            "delivery companies should invest more funds in proven long-distance transport technologies than in untested last-mile solutions.",
            "innovations in last-mile logistics seem poised to increase consumers' expectations for rapid delivery."
          ],
          "answer": 1
        },
        {
          "id": 15,
          "passage": "Microbial fuel cells (MFCs) capitalize on the ability of some species of bacteria to metabolize metal, liberating electrons. The bacteria form a dense biofilm on the surface of an electron-collecting anode, but moving the electrons from the bacterial cytoplasm to an external electrode requires that the electrons pass through a series of inefficient oxidation-reduction (redox) reactions. Accordingly, MFC power output rarely exceeds a density of 0.30 milliwatts per square centimeter (mW/cm²). In an experiment, researchers added silver nanoparticles to carbon paper covering the anode in an MFC. The resulting power density was 0.66 mW/cm². Since metals such as silver exhibit high electrical conductivity, the researchers hypothesized that _______",
          "question": "Which choice most logically completes the text?",
          "options": [
            "silver nanoparticles may allow electrons to bypass the series of redox reactions and transfer directly to the electrode.",
            "as the density of the biofilm increases, the series of redox reactions may accelerate independent of the presence of the silver nanoparticles.",
            "electrons may be conducted directly to the electrode before the silver nanoparticles catalyze the redox reactions.",
            "silver nanoparticles may increase the metabolic processes of the bacteria, thereby increasing the number of free electrons available to transfer to the electrode."
          ],
          "answer": 0
        },
        {
          "id": 16,
          "passage": "The ratio of methane to other atmospheric constituents—represented by a measure called the methane mole fraction—influences a variety of meteorological phenomena, notably precipitation and humidity. For Titan, Saturn's largest moon, the observational data that exist are too sparse and discrepant to fully constrain the range of the methane mole fraction at various atmospheric levels. Juan Lora and colleagues point out that outputs of the IPSL atmospheric model of Titan, which track closely to observations in some respects, reflect how the model's developers responded to this challenge: by prescribing a uniform methane mole fraction for the lowest level of the atmosphere. It is therefore important to note that ______",
          "question": "Which choice most logically completes the text?",
          "options": [
            "further observations of Titan may clarify the moon's methane mole fraction sufficiently for the model to employ a single value rather than a range.",
            "some disagreements between the model's simulations of Titan's precipitation and humidity and the moon's actual precipitation and humidity are to be expected.",
            "even though the model's outputs sometimes agree with observational data, Titan's real methane mole fraction is likely higher than the methane mole fraction used in the model.",
            "inconsistencies across the model's simulations of Titan's precipitation and humidity could be attributable to variations in the moon's methane mole fraction."
          ],
          "answer": 1
        },
        {
          "id": 17,
          "passage": "New Zealand and Greece have two of the longest constitutions in the world. At 48,438 and 26,989 words, respectively, these ____ according to research by constitutional scholars George Tsebelis and Dominic J. Nardi, correlate with GDPs (gross domestic products) that are lower than those of countries with shorter constitutions.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "constitutions lengths,",
            "constitution's length,",
            "constitutions' lengths,",
            "constitutions' length,"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 18,
          "passage": "Included in Second sight: the Paradox of Vision in Contemporary Art, a 2018 group exhibition at the Bowdoin College Museum of Art in Brunswick, Maine, was the work of artist Lorna Simpson, who is best known for her multimedia artworks that juxtapose images of African American women with text fragments. Her work challenges conventional notions of race, gender, history, and _____ she is credited with expanding the horizons of conceptual photographic art.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "memory,",
            "memory",
            "memory, and",
            "memory and"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 19,
          "passage": "Recent analysis of 54598 Bienor—an outer solar system object orbiting the Sun between Saturn and Uranus—has determined its color to be gray, suggesting an icy composition. Such interpretations are ultimately _____ the object's gray coloration may be an incidental effect of radiation, solar wind, or collisions with other objects rather than evidence of its physical makeup.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "speculative, though,",
            "speculative, though;",
            "speculative; though",
            "speculative, though"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 20,
          "passage": "Mitochondrial genomes reproduce asexually, which should over time result in an accumulation of harmful mutations and a decline in mitochondrial functionality. However, nuclear genes are hypothesized to coevolve with the rate of mitochondrial decline, eliminating mutational erosion. Such a compensatory measure _______ the organelle's decline, unlike enzyme-stabilizing accessory proteins, offers an evolutionary explanation of mitochondrial reproduction.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "counteracts",
            "had counteracted",
            "counteracted",
            "counteracting"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 21,
          "passage": "In the list \"Adorable Things\" from Sei Shōnagon's Pillow Book, the author delights in baby sparrows, a face drawn on a melon, and a young courtier in ceremonial garb. So shrewd an observer is Shōnagon, a lady-in-waiting to Empress Teishi, that her book's musings on tenth-century Japanese courtly life _____ readers a thousand years later.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "has fascinated",
            "fascinates",
            "is fascinating",
            "fascinate"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 22,
          "passage": "To notice subtle variations in the progression of the still life painting genre in Europe, first consider Abraham Mignon's \"Still Life with Fruit and a Beaker on a Cock's Foot\" from 1669; _____ compare it to Jean-Siméon Chardin's \"Still Life with Herrings\" from 1735.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "instead,",
            "therefore,",
            "next,",
            "still,"
          ],
          "answer": 2,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 23,
          "passage": "In an ekphrastic poem, a poet explores a work of visual art, such as a drawing, sculpture, or painting. Robert Hayden's 1994 poem \"Monet's Waterlilies,\" for example, meditates on Claude Monet's 1899 painting Water Lilies; Elizabeth Alexander's 2001 poem \"Islands Number Four,\" _____ takes a painting as its subject: Agnes Martin's 1961 work Islands No. 4.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "conversely,",
            "nevertheless,",
            "hence,",
            "likewise,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 24,
          "passage": "While researching a topic, a student has taken the following notes: • In a 2004 study, researchers Jorge E. López and C. Vaughan wanted to explore the effects of ingestion by bats on the germination of Piper sancti-felicis seeds in Costa Rica. • The team of researchers tested 125 Piper sancti-felicis seeds that had been ingested by chestnut short-tailed bats. • Of these, 82 seeds (66%) germinated. • AS a control, J.E. López and C. Vaughan tested 125 Piper sancti-felicis seeds that had not been ingested by chestnut short-tailed bats. • Of these, 88 seeds (70%) germinated.",
          "question": "The student wants to describe the study's research methodology. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "The team of researchers tested the germination of 125 Piper sancti-felicis seeds that had been ingested by chestnut short-tailed bats and 125 Piper sancti-felicis seeds that had not been ingested.",
            "J.E López and C. Vaughan wanted to explore the effects of chestnut short-tailed bats' ingestion on Piper sancti-felicis seed germination.",
            "In the study, a lower percentage of Piper sancti-felicis seeds ingested by bats germinated than those that had not been ingested by bats.",
            "Research by J.E. López and C. Vaughan revealed that 82 of 125—that is, 66%—of the Piper sancti-felicis seeds that had been ingested by the bats germinated."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 25,
          "passage": "While researching a topic, a student has taken the following notes: • Felipe Posada (pseudonym The Invisible Realm) is a New York City-based artist who specializes in the form of art known as surrealist collage. • Manifestation of the unconscious mind is a central aspect of surrealist collage. • Irrational juxtaposition of disparate elements is a central aspect of surrealist collage. • Posada's High Maintenance irrationally juxtaposes images of an astronaut, a giant human face, and a waterfall. • Posada: \"My art is a journey through the invisible realm—a space where intuition, memories, visions, and dreams are free to take visual form.\"",
          "question": "The student wants to provide a specific example of irrational juxtaposition in surrealist collage. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Surrealist collage, such as Felipe Posada's High Maintenance, manifests the unconscious mind and irrationally juxtaposes disparate elements.",
            "Images of an astronaut, a giant human face, and a waterfall are juxtaposed irrationally in the surrealist collage piece High Maintenance by artist Felipe Posada.",
            "High Maintenance by artist Felipe Posada is an example of surrealist collage, a form in which irrational juxtaposition is a central aspect.",
            "The irrational juxtaposition of disparate elements in Felipe Posada's art invokes \"a space where intuition, memories, visions, and dreams are free to take visual form.\""
          ],
          "answer": 1,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 26,
          "passage": "While researching a topic, a student has taken the following notes: • Carbon can exist in several distinct structural forms called allotropes. • Graphite is a carbon allotrope. • Graphite is composed of stacked graphene sheets. • Each graphene sheet is composed of carbon atoms arranged in a flat honeycomb pattern. • Carbon nanotubes are carbon allotropes. • They are composed of one or more graphene sheets wrapped into a cylindrical shape.",
          "question": "The student wants to emphasize a difference between carbon nanotubes and graphite. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Composed of sheets wrapped into a cylindrical shape, carbon nanotubes contrast with graphite, a carbon allotrope composed of graphene sheets.",
            "Unlike carbon nanotubes, which are composed of sheets of carbon atoms arranged in a flat honeycomb pattern, graphite is a cylindrical carbon allotrope.",
            "The graphene sheets in graphite are stacked, whereas in carbon nanotubes, they form a cylinder.",
            "Graphite and carbon nanotubes are allotropes composed of stacked or wrapped graphene sheets, but carbon can exist in several distinct structural forms."
          ],
          "answer": 2,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes: • Modularity of mind is the notion that the mind is at least partly composed of innate neural structures (modules) that perform fast, necessary tasks. • 1983: cognitive scientist Jerry A. Fodor hypothesized that low-level cognitive systems (e.g., perception, language) are modular. • In Fodorian modularity, high-level systems (e.g., reasoning) are not modular. • 2003: cognitive scientist Peter Carruthers proposed the massive modularity hypothesis (MMH). • MMH expands modularity to include all cognitive systems.",
          "question": "The student wants to compare Fodor's hypothesis with Carruthers's. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "In considering some but not all cognitive systems modular, Fodorian modularity is not as expansive in its definition of modularity as MMH is.",
            "The hypotheses of Fodor and Carruthers differ in whether they consider low-level cognitive systems, such as perception and language, modular.",
            "In 2003, Carruthers proposed the massive modularity hypothesis, disagreeing with Fodor's earlier hypothesis that the mind is composed of innate neural structures.",
            "Following Fodor's 1983 hypothesis, Carruthers proposed that modularity of mind includes all cognitive systems."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    }
  ]
} satisfies MockTestSet
