// Generated from sat-cmp-2024-h8-int-04-module-1.json, sat-cmp-2024-h8-int-04-module-2.json
// Review answers and images before publishing.

import type { MockTestSet } from '../mockTestQuestions'

export const importedMockTest = {
  "id": "sat-cmp-2024-h8-int-04",
  "title": "SAT CMP 2024-H8-INT-04(读写)",
  "year": 2024,
  "modules": [
    {
      "name": "Module 1 (Routing)",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "The reception of Many Ly's book Roots and Wings has been very good. Many reviewers, booksellers, and librarians have __________ the book, and it won the Asian/Pacific American Award for Literature.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "attacked",
            "recommended",
            "overlooked",
            "misunderstood"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 2,
          "passage": "The following text is adapted from Mary Seacole's 1857 autobiography Wonderful Adventures of Mrs. Seacole in Many Lands. That journey across the Isthmus [of Panama], insignificant in distance as it was, was by no means an easy one. It seemed as if nature had determined to throw every conceivable obstacle in the way of those who should seek to join the two great oceans of the world.",
          "question": "As used in the text, what does the word \"conceivable\" most nearly mean?",
          "options": [
            "Visible",
            "Steady",
            "Easy",
            "Possible"
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Words in Context",
          "underline": [
            "conceivable"
          ]
        },
        {
          "id": 3,
          "passage": "Kelp forests grow underwater along the eastern Pacific Coast. These underwater forests are important to fish and other marine animals. Ocean currents can be powerful and rough, making it difficult for animals to find safe places to hide from predators. The underwater forests slow down the currents. This creates a more __________ environment with calmer waters where animals can take shelter.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "surprising",
            "dangerous",
            "tranquil",
            "imaginative"
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "The recently observed gamma ray burst GRB 230307A lasted for 200 seconds, __________ for a burst generated by the merger of neutron stars. Bursts caused by neutron mergers typically last fewer than 2 seconds.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "an oddity",
            "a coincidence",
            "a reprieve",
            "an incident"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "Pteropods are small swimming snails with thin, delicate calcium carbonate shells. These animals are thought to be especially vulnerable to ocean acidification due to calcium carbonate's susceptibility to dissolution at lower pH values. Victoria L. Peck and colleagues recently found that the periostracum (a protective coating on pteropods' outer shells) prevents this dissolution when intact. Moreover, the team was surprised to discover that even when the periostracum is breached, pteropods can still mitigate damage by rebuilding the inner shell wall.",
          "question": "Which choice best describes the main purpose of the text?",
          "options": [
            "To call for additional research on biological mechanisms that improve pteropod survival rates",
            "To present findings that suggest that a concern about the effects of ocean acidification on pteropod shells may be unwarranted",
            "To address some of the ways ocean acidification has altered pteropod behavior over time",
            "To discuss a conclusion drawn in a study of calcium carbonate's role in protecting the periostracum of pteropods"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 6,
          "passage": "San Francisco has high pedestrian traffic, but simply replicating a feature of San Francisco associated with walkability—e.g., its high density of storefronts—may be insufficient to induce increased walking in other cities. As urbanist Mariela Alfonzo argues, our understanding of individuals' decision-making about whether to walk is insufficiently robust: some studies emphasize the role of demographic characteristics, others the role of public transit availability, and so on, but walking decisions are made in complex contexts in which multiple conditions and needs inform individuals' choices.",
          "question": "Which choice best describes the main purpose of the text?",
          "options": [
            "To discuss the difficulty of identifying a reliable way to increase walking in any given city",
            "To explain why it is challenging to compare the amount of pedestrian traffic indifferent cities",
            "To describe the effect of a high density of storefronts on any given city's walkability",
            "To present a claim about how individuals' decision-making about walking can be improved"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 7,
          "passage": "Guojun He and colleagues studied a food-delivery phone app that is popular in China. The researchers found that having \"no cutlery\" automatically selected influences whether customers request disposable plastic utensils with their food orders. Based on their results, the researchers concluded that this and other small changes to the app could reduce plastic waste in China by as much as 3.26 million metric tons per year.",
          "question": "According to the text, which choice best describes a conclusion He and colleagues drew from their study?",
          "options": [
            "Production of plastic waste in China is likely to increase in the near future.",
            "Food-delivery apps that prevent customers from requesting cutlery are becoming more popular.",
            "Customers who understand how food-delivery apps work make more environmentally friendly choices.",
            "Small changes to how a food-delivery app works can greatly lower plastic waste."
          ],
          "answer": 3
        },
        {
          "id": 8,
          "passage": "The following text is from William Shakespeare's play The Tempest, first performed in 1611. Miranda has lived on an island with her father, Prospero, since she was three years old. Prospero has stated that Miranda likely does not remember anything other than her life on the island. MIRANDA: 'Tis far off, And rather like a dream than an assurance That my remembrance warrants. Had I not Four or five women once that tended me? PROSPERO: Thou hadst, and more, Miranda. But how is it That this lives in thy mind? What seest thou else In the dark backward and abysm of time? If thou remember'st ought ere thou camest here, How thou camest here thou mayst.",
          "question": "In the text, which point does Prospero most directly make about Miranda and her memories?",
          "options": [
            "Miranda's impression of a scene is vague because she is remembering a scenario she had daydreamed about as a child rather than a scenario that had occurred in reality.",
            "Miranda's reminiscences about her early childhood have a melancholy quality that betrays her discontented view of her current circumstances.",
            "Miranda's ability to summon details of an experience she had before arriving on the island suggests that she may also be able to summon details of her arrival on the island.",
            "Miranda's doubts about the accuracy of one recollection of a place other than the island are clouding her judgment and seem to be making her reluctant to explore her recollection of traveling to the island."
          ],
          "answer": 2
        },
        {
          "id": 9,
          "passage": "The Chickasaw Nation and the nearly forty other tribes in Oklahoma operate numerous businesses and collectively generate billions of dollars in revenue. Mining, including oil and natural gas production, is a key industry in the state as well. While researching other key industries in Oklahoma for an economics class, a student finds that the average amount contributed to the state's economy in 2017 by each individual employed in wholesale trade was __________",
          "question": "Which choice most effectively uses data from the table to complete the statement?",
          "options": [
            "$141,510.",
            "$56,163.",
            "$183,790.",
            "$96,964."
          ],
          "answer": 2,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Impact of Four Key Industries on Oklahoma Economy in 2017",
            "headers": [
              "Industry",
              "Approximate total contribution by industry",
              "Number of people employed by industry",
              "Average contribution per employee by industry"
            ],
            "rows": [
              [
                "Tribal economic activity",
                "$7,312,400,000",
                "51,674",
                "$141,510"
              ],
              [
                "Finance/insurance",
                "$7,281,900,000",
                "56,163",
                "$129,657"
              ],
              [
                "Wholesale trade",
                "$10,723,400,000",
                "58,346",
                "$183,790"
              ],
              [
                "Administration/waste",
                "$5,830,600,000",
                "96,964",
                "$60,132"
              ]
            ]
          }
        },
        {
          "id": 10,
          "passage": "A marine biologist is researching four stony coral species in Caribbean and Indo-Pacific waters, focusing on sightings of these species in the shallow zone (less than 30 meters below the surface) and the mesophotic zone (30 to 150 meters below the surface). Consulting the table, she notes that the smallest maximum depth is located in __________",
          "question": "Which choice most effectively uses data from the table to complete the statement?",
          "options": [
            "Indo-Pacific waters in the shallow zone.",
            "Caribbean waters in the shallow zone.",
            "Indo-Pacific waters in the mesophotic zone.",
            "Caribbean waters in the mesophotic zone."
          ],
          "answer": 0,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Minimum and Maximum Depths of Stony Coral Species in Caribbean and Indo-Pacific Waters",
            "headers": [
              "Species",
              "Location",
              "Minimum depth (meters)",
              "Maximum depth (meters)"
            ],
            "rows": [
              [
                "Agaricia grahamae",
                "Caribbean",
                "20",
                "115"
              ],
              [
                "Acropora bushyensis",
                "Indo-Pacific",
                "0",
                "5"
              ],
              [
                "Mussa angulosa",
                "Caribbean",
                "5",
                "30"
              ],
              [
                "Indophyllia macassarensis",
                "Indo-Pacific",
                "20",
                "25"
              ]
            ]
          }
        },
        {
          "id": 11,
          "passage": "In a college course on urban affairs, a student asserts that increased traffic congestion in the United States in the 1990s was present both in very large cities such as Philadelphia, Pennsylvania, and smaller areas such as Albany-Schenectady-Troy, New York, and Beaumont, Texas; though those smaller areas may have been less affected by traffic congestion than very large cities, this congestion also worsened in them over time.",
          "question": "Which choice best describes data from the graph that support the student's claim?",
          "options": [
            "Even though the amount of traffic delay per commuter per year was greater in the Albany-Schenectady-Troy, New York, area than in the Philadelphia, Pennsylvania, area throughout the period from 1990 to 2000, the amounts were nearly identical in 1996.",
            "In 1992, the amount of traffic delay in the Philadelphia, Pennsylvania, area was less than 30 hours per commuter per year.",
            "In at least one of the three urban areas shown, the amount of traffic delay was less than 20 hours per commuter per year at one point between 1990 and 2000.",
            "While the annual number of hours of traffic delay per commuter was always lower in the Albany-Schenectady-Troy, New York, area than in the Philadelphia, Pennsylvania, area for each year between 1990 and 2000, the amount of traffic delay rose in both areas during this period."
          ],
          "answer": 3,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "image": "/sat-cmp-2024-h8-int-04-m1-q11.svg"
        },
        {
          "id": 12,
          "passage": "Past research suggests that pollination by honeybees is responsible for up to 10 percent of total Chinese cabbage crop production. Now researchers are trying to determine how dependent cucumber crop production is on honeybees. The first phase of their study involved shielding some cucumber plants to prevent insects from pollinating them, resulting in those plants having 40 to 90 percent lower crop production than plants that were pollinated normally. However, the researchers claim that the first-phase experiment alone didn't tell them how much of that difference in crop production is due specifically to excluding honeybees.",
          "question": "Which finding, if true, would most directly support the researchers' claim?",
          "options": [
            "The shielding used in the first phase of the study did not affect the amount of sunlight the cucumber plants received.",
            "Other insects like solitary bees also pollinate Chinese cabbage plants, and some studies have allowed them to pollinate normally while excluding honeybees.",
            "Other insects like squash bees also pollinate cucumber plants, and the shielding in the first phase of the study blocked them as well.",
            "Honeybees are more commonly used to pollinate cucumber plants than Chinese cabbage plants."
          ],
          "answer": 2
        },
        {
          "id": 13,
          "passage": "The glossy ibis and the small dark heron are long-legged birds that live in wetlands, like the Everglades in Florida. Laura D'Acunto and colleagues wanted to know how these birds choose an area in which to live. They looked at features of the birds' habitats, such as the geographic location of the area and how deep the water is during the birds' breeding season. They found that glossy ibises prefer areas with deep water during breeding season, but that was not true for small dark herons. The researchers concluded that water management strategies that increase the depth of water in potential wetland bird habitats during breeding season are therefore more likely to __________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "attract glossy ibises to the area than they are to attract small dark herons to the area.",
            "attract birds that don't typically live in wetlands to the area than they are to attract glossy ibises or small dark herons to the area.",
            "extend the average lifespan of glossy ibises already in the area than they are to attract a greater number of those birds to the area.",
            "decrease the area's appeal to both glossy ibises and small dark herons than they are to increase the appeal to either."
          ],
          "answer": 0
        },
        {
          "id": 14,
          "passage": "Scientists recently created a model to predict how increasing human activity will affect future mammal population sizes in US national forests. Unfortunately, when the model is applied to large forests, its predictions for large-mammal populations are too high, and when applied to small forests, its predictions for small-mammal populations are too high. Beaverhead-Deerlodge National Forest in Montana is a large forest, covering more than 3 million acres. If used to evaluate the effect of increasing human activity on this forest in ten years, the model would likely therefore __________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "exaggerate the effect of increasing human activity on small mammals.",
            "overestimate the actual population sizes of large mammals.",
            "ignore the predator-prey relationships between large and small mammals.",
            "reflect factors affecting large mammals other than increasing human activity."
          ],
          "answer": 1
        },
        {
          "id": 15,
          "passage": "In 1989, Missouri __________ official fossil: the Eperisocrinus missouriensis, which is a Carboniferous period marine animal.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "lawmaker's designated the states",
            "lawmakers designated the state's",
            "lawmaker's designated the state's",
            "lawmakers designated the states"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 16,
          "passage": "Often anthologized alongside the __________ associated with the Black Arts movement—such as Henry Dumas and Ntozake Shange—Haki Madhubuti's poem \"Quality: Gwendolyn Brooks at 73\" stands out for its memorable first lines: \"breath, / life after seven decades plus three years / is a lot of breathing.\"",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "works of other writer's",
            "work's of other writer's",
            "works of other writers",
            "work's of other writers"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 17,
          "passage": "The part of a compound that determines the compound's color is __________ the chromophore. One example of a chromophore is hemoglobin, which gives human blood its red color.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "called—",
            "called;",
            "called,",
            "called"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 18,
          "passage": "Released in 1993, the Intel Pentium microchip contained a single CPU, or core, to execute commands. Since then, the average processing power of microchips has increased so drastically—cores now number in the dozens, hundreds, or even __________ the once-revolutionary dual-core technology that replaced the single-core chip can be found in everyday items like toasters and toothbrushes.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "thousands—that",
            "thousands that—",
            "thousands. That",
            "thousands, that"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 19,
          "passage": "After finding information about Ronald V. Dellums, who represented California in the United States House of Representatives, the student discovered biographical sketches of two other Black Americans who served in __________ Ralph Harold Metcalfe of Illinois and George Henry White of North Carolina.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "Congress.",
            "Congress:",
            "Congress;",
            "Congress"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 20,
          "passage": "When a given industry—water and electricity are two well-known examples—carries high infrastructural start-up costs and other barriers that discourage competition, __________ of just one or two suppliers per municipality. Such industries are known as natural monopolies.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "they often consist",
            "this often consists",
            "these often consist",
            "it often consists"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 21,
          "passage": "Cornelia Konrads is a German sculptor who creates art that seems to be part of its surroundings. Her sculpture entitled knotty stilts is built on the wall of a university building in the United States. __________ appearing as two support beams knotted together against the wall, it is cleverly placed into its environment, serving as an example of Konrads's approach.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "There,",
            "Later,",
            "For instance,",
            "However,"
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 22,
          "passage": "There are three basic steps you should follow when planning a scientific inquiry. First, thoroughly research the question you wish to answer. __________ come up with a prediction (also called a hypothesis) about the answer to your question. Third, develop an experiment that can test the accuracy of your hypothesis.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "For example,",
            "Second,",
            "Therefore,",
            "Instead,"
          ],
          "answer": 1,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 23,
          "passage": "Upon first approaching artist Kurt Wenner's Dies Irae, a colorful scene painted on the surface of a cobblestone street in Mantua, Italy, one might assume a deep hole filled with life-sized, classically styled sculptures had opened up in the street. __________ by expertly applying the principles of perspective, Wenner created merely the illusion of depth.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "Additionally,",
            "Next,",
            "As a result,",
            "On the contrary,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 24,
          "passage": "While researching a topic, a student has taken the following notes: • Atitalaquia is a municipality in the state of Hidalgo, Mexico. • Municipalities are governmental regions responsible for providing many public services to their residents. • One service they provide is street lighting. • Atitalaquia covers an area of roughly 63 km2. • Hidalgo is divided into 84 municipalities.",
          "question": "The student wants to emphasize the size of Atitalaquia. Which choice most effectively use relevant information from the notes to accomplish this goal?",
          "options": [
            "Providing street lighting is just one example of the public services that municipalities provide.",
            "Atitalaquia is one of 84 governmental regions, known as municipalities, across Hidalgo.",
            "Atitalaquia—a governmental region in the state of Hidalgo, Mexico—provides many public services to its residents.",
            "The municipality of Atitalaquia in Hidalgo, Mexico, covers an area of roughly 63 km2."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 25,
          "passage": "While researching a topic, a student has taken the following notes: • The Future of Nostalgia is a scholarly book by literary theorist Svetlana Boym. • The book provides a multifaceted exploration of the concept of nostalgia. • Chapter 9 describes nostalgia in the city of St. Petersburg in Russia. • Chapter 17 discusses various skeptics' takes on the concept of nostalgia. • In chapter 17, Boym writes, \"The poethics of nostalgia combines estrangement and human solidarity, affect and reflection.\"",
          "question": "The student wants to provide a quotation from chapter 17. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "In a discussion of various skeptics' takes on the concept of nostalgia, Svetlana Boym writes, \"The poethics of nostalgia combines estrangement and human solidarity, affect and reflection.\"",
            "Svetlana Boym's The Future of Nostalgia provides a multifaceted exploration of nostalgia.",
            "Svetlana Boym describes nostalgia in the city of St. Petersburg in Russia in chapter 9 of her book.",
            "After describing nostalgia in the city of St. Petersburg in Russia, Svetlana Boym goes on to discuss various skeptics' takes on the concept of nostalgia."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 26,
          "passage": "• Jean-Michel Basquiat was an American artist who produced more than two thousand drawings and paintings. • His work Untitled (Two Heads on Gold) was completed in 1982 and sold at auction in 2003. • Untitled (Two Heads on Gold) is composed of acrylic and oil stick on canvas and measures 10,000 square inches in area. • His work Jazz was completed in 1986 and sold at auction in 2020. • Jazz is composed of acrylic, oil, graphite, crayon, and paper collage on wood and measures 1,807 square inches in area.",
          "question": "Which choice most effectively uses information from the given sentences to emphasize how the two works are similar?",
          "options": [
            "Artist Jean-Michel Basquiat completed Untitled (Two Heads on Gold) in 1982, and Jazz followed in 1986.",
            "Between artist Jean-Michel Basguiat's works Untitled (Two Heads on Gold) and Jazz, the former is the larger of the two.",
            "Composed by artist Jean-Michel Basquiat in 1982 and 1986, respectively, both Untitled (Two Heads on Gold) and Jazz use acrylic paint as a medium.",
            "Artist Jean-Michel Bascuiat's work Untitled (Two Heads on Gold) is composed of acrylic and oil stick, while Jazz is composed of acrylic, oil, graphite, crayon, and paper collage."
          ],
          "answer": 2,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes: • Onomatopoeias are words that imitate the sounds they represent. • Words that represent the same sound are often written and pronounced very differently from language to language. • This variation is due in part to differences in how the languages are structured. • \"Korrrr\" is a Batak onomatopoeia that represents the sound of snoring. • \"Hü lu\" is a Mandarin Chinese onomatopoeia that represents the sound of snoring.",
          "question": "The student wants to contrast two words that represent the same sound. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Though they both represent the sound of snoring, the onomatopoeias \"korrrr\" (Batak) and \"hü lu\" (Mandarin Chinese) are written and pronounced very differently.",
            "Onomatopoeias, words that imitate the sounds they represent, are often written and pronounced very differently from language to language.",
            "The Batak word \"korrrr\" and the Mandarin Chinese word \"hü lu\" are onomatopoeias that represent the sound of snoring.",
            "The Batak word \"korrrr,\" which represents the sound of snoring, is an onomatopoeia."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    },
    {
      "name": "Module 2",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "The following text is adapted from William Wordsworth's 1798 poem \"Lines Written a Few Miles above Tintern Abbey.\" Once again Do I behold these steep and lofty cliffs, Which on a wild secluded scene impress Thoughts of more deep seclusion; and connect The landscape with the quiet of the sky.",
          "question": "As used in the text, what does the word \"behold\" most nearly mean?",
          "options": [
            "Regard",
            "Possess",
            "Escape",
            "Neglect"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context",
          "underline": [
            "behold"
          ]
        },
        {
          "id": 2,
          "passage": "The decline of the giant ground sloth, a species found throughout South America before it became extinct around 8500 BCE, surely had a number of __________ the larger ecosystem in which it existed. The giant ground sloth was part of a complex food web with other organisms, and its disappearance likely affected several other species.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "sources in",
            "consequences for",
            "similarities to",
            "precedents in"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 3,
          "passage": "Writer Lydia Davis observed that while __________ literary forms, such as the short story, are recognizable as such even as they evolve, there are rarer \"intergeneric\" forms that might, for example, use elements of both fiction and essays to create something unclassifiable. Anne Carson's collection Float arguably fits in this category, since it straddles the line between prose and poetry.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "neutral",
            "equivocal",
            "intermediate",
            "orthodox"
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "Although our knowledge of the Pliocene epoch and the lives of hominids during this time was once __________, recent analyses of fossils like that of the individual known as LH 4, discovered in Tanzania in 1974, have sharpened our picture of what a day in the life of LH 4 may have looked like.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "unprecedented",
            "nebulous",
            "intricate",
            "concrete"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "President Richard Nixon is most famous for his participation in the 1970s Watergate political scandal, a convoluted tale of criminality and eroded ethics involving a constellation of associates such as political operative Jeb Stuart Magruder and Nixon's secretary Rose Mary Woods. But Nixon's legacy is complex: he has been praised for his role in affirming the sovereignty of tribal nations, and he once made an attempt at reforming United States health care policy that is arguably a precursor to the Affordable Care Act, which became law during the Barack Obama administration.",
          "question": "Which choice best describes the overall structure of the text?",
          "options": [
            "An achievement of a historical figure is described, and then reasons why that achievement is often disregarded by historians are suggested.",
            "Information supporting a particular perception of a historical figure is provided, and then additional facts are offered suggesting that this perception is an oversimplification.",
            "A list of historical figures is presented, followed by reasons why one should be considered more significant than the others.",
            "An assertion about a historical figure is made, and then evidence both for and against that assertion is presented."
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 6,
          "passage": "In a study by Mika R. Moran, Daniel A. Rodriguez, and colleagues, residents of Panama City, Panama, and Caracas, Venezuela, were surveyed about parks in their cities. Of the 318 respondents from Panama City, 53.5% indicated that they use the city's parks, and of the 1,043 respondents from Caracas, 44.7% indicated using city parks. Given that the percentage of Panama City respondents who reported having access to desired nonpark amenities near parks was much lower than that reported by Caracas respondents, the difference in park use can't be explained by Panama City residents having more access to desired nonpark amenities near parks.",
          "question": "Which choice best describes the overall structure of the text?",
          "options": [
            "An unexpected finding is described, and then that finding is attributed to the method used to collect survey data in Panama City and Caracas.",
            "An unresolved question about park planning is described, and then examples from a study of Panama City and Caracas are used to answer that question.",
            "A study involving surveys in Panama City and Caracas is introduced, and then a possible explanation for some of the results is considered and rejected.",
            "A study of park use in Panama City is described, and then a similar study of park use in Caracas is analyzed to corroborate the findings of the Panama City study."
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 7,
          "passage": "The following text is from Jerome K. Jerome's 1889 novel Three Men in a Boat (To Say Nothing of the Dog). The narrator and two friends are taking a boat down the River Thames in England. In a boat, I have always noticed that it is the fixed idea of each member of the crew that he is doing everything. Harris's notion was, that it was he alone who had been working, and that both George and I had been imposing upon him. George, on the other hand, ridiculed the idea of Harris's having done anything more than eat and sleep, and had a cast-iron opinion that it was he—George himself—who had done all the labour worth speaking of.",
          "question": "Which choice best describes the main purpose of the text?",
          "options": [
            "To address a particular situation that the narrator finds unexpected",
            "To convey the narrator's confidence that he understands the role expected of him in a group",
            "To examine how the narrator and his friends each contributed to navigating a challenge",
            "To present the narrator's generalization along with supporting examples from a specific situation"
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 8,
          "passage": "Text 1 The poet Audre Lorde once claimed that poetry is the most inexpensive of art forms to practice. While people who pursue other art forms—painting, architecture, theater—require large blocks of uninterrupted time as well as money to complete their work, poets can write, as Lorde said, \"between shifts, in the hospital pantry, on the subway, and on scraps of surplus paper.\" So poets can practice their art even if they must earn their living in another way. Text 2 Any assessment of the state of contemporary poetry must reckon with the professionalization of the field. While it is possible in theory for anyone to publish in Virginia Quarterly Review, Kenyon Review, or a similar major poetry outlet, many people who do so have professional training in poetry and extensive practice writing it, which requires time not often available to those who must also work full-time jobs. Thus, financial security indirectly affects which people become poets.",
          "question": "Based on the texts, Lorde (Text 1) and the author of Text 2 would most likely disagree about the answer to which of the following questions?",
          "options": [
            "Do other art forms than poetry require substantial investments of time and money?",
            "Should poets try to gain experience working in nonartistic fields as a way of improving their poetry?",
            "Does professional training in poetry affect the quality of poets' work?",
            "Is working a full-time job a major impediment to practicing the art of poetry?"
          ],
          "answer": 3
        },
        {
          "id": 9,
          "passage": "The following text is from Ralph Waldo Emerson's 1841 essay \"The Method of Nature.\" The scholars are the priests of that thought which establishes the foundations of the earth. No matter what is their special work or profession, they stand for the spiritual interest of the world, and it is a common calamity if they neglect their post in a country where the material interest is so predominant as it is in America.",
          "question": "Which choice best states the main idea of the text?",
          "options": [
            "Military experience encourages Americans to contemplate aspects of human life that they would not choose to otherwise.",
            "It is unfortunate that so many intellectuals are concerned with material things rather than ideas.",
            "Many descriptions of the role of scholars in society unfairly diminish their importance.",
            "In a country whose citizens are largely preoccupied with tangible gains, it is crucial that some people work to foster and preserve ideas."
          ],
          "answer": 3
        },
        {
          "id": 10,
          "passage": "At over a thousand pages across two volumes, The Fifty-Year Mission, compiled by Edward Gross and Mark A. Altman, is presented as the \"complete, uncensored, unauthorized oral history\" as told by the people behind the media franchise Star Trek. The work aspires to be comprehensive by, for example, including accounts from cast and crew members of every Star Trek television series and film to date. But while The Fifty-Year Mission is clearly a unique and valuable resource, it has a shortcoming common among oral histories: it lacks a clear authorial point of view that could otherwise unite the various accounts into a cohesive whole.",
          "question": "Which choice best states the main idea of the text?",
          "options": [
            "The Fifty-Year Mission includes more accounts from people involved with Star Trek television shows than it does from people involved with Star Trek films.",
            "The compilers of The Fifty-Year Mission had lofty goals for their oral history of the Star Trek franchise, but the published work lacks information about many key events in the franchise's history.",
            "The large amount of material compiled into The Fifty-Year Mission is surprising given that many of the people involved in the Star Trek franchise did not participate in the oral history project.",
            "The Fifty-Year Mission represents a worthwhile attempt to thoroughly recount the history of the Star Trek franchise, but its approach has an important limitation."
          ],
          "answer": 3
        },
        {
          "id": 11,
          "passage": "Water flowing around an obstruction creates vortices (swirls) that vary in size with the obstruction's size and position, and fish sense these vortices in order to navigate around the obstructions. Using models of three fish-head shapes—narrow (low ratio of width to length), intermediate, and wide (high ratio of width to length)—Yuzo R. Yanagisuru, Otar Akanyeti, and James C. Liao showed that as vortex size increases, pressure fluctuations at the snout increase for narrow-headed and intermediate-headed fish but remain low for wide-headed fish. A second research team has therefore hypothesized that in low visibility, a fish will be more likely to avoid an obstruction when the associated pressure fluctuations at the fish's snout are greater.",
          "question": "Which finding, if true, would most directly challenge the second research team's hypothesis?",
          "options": [
            "A study using obstructions that created large vortices in low-visibility conditions found that the Synodontis macropunctata, which has a relatively wide head, bumped into less than half of the obstructions.",
            "A study using obstructions that created large vortices in low-visibility conditions found that the intermediate-headed dusky smooth-hound (Mustelus canis) bumped into the obstructions just as often as the wide-headed Synodontis macropunctata did.",
            "A study using obstructions that created large vortices in low-visibility conditions found that the wide-headed Synodontis macropunctata bumped into obstructions more often than the intermediate-headed dusky smooth-hound (Mustelus canis) did.",
            "A study using obstructions that created large vortices in low-visibility conditions found that some specimens of the intermediate-headed dusky smooth-hound (Mustelus canis) bumped into the obstructions more often than others did."
          ],
          "answer": 1
        },
        {
          "id": 12,
          "passage": "In a study of the evolution of DptA and DptB—Diptericin genes encoding antimicrobial peptides that combat pathogens and foster beneficial microbes in fruit flies (Drosophila)—researchers assessed Drosophila melanogaster resistance to pathogenic infections by Providencia rettgeri and Acetobacter sicerae, bacteria common in the flies'environments. Subjects included flies identifed by mutations silencing DptA, DptB, or both DptA and DptB (termed types A, B, and AB, respectively). In conjunction with the observation that resistance to P. rettgeri correlates with DptA activity but is not significantly affected by DptB activity, data in the graph of survival rates post-A. sicerae infection suggest that",
          "question": "Which completion of the text is best supported by data in the graph?",
          "options": [
            "DptA confers defense against A. sicerae regardless of the presence of DptB.",
            "DptB may have developed as a specific defense against A. sicerae.",
            "DptB protects against only one bacteria species, whereas DptA protects against multiple species.",
            "defense against A. sicerae is strongest when both DptA and DptB are present."
          ],
          "answer": 1,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "image": "/sat-cmp-2024-h8-int-04-m2-q12.svg"
        },
        {
          "id": 13,
          "passage": "Neurobiologists Laura Cuaya, Raúl Hernandez-Pérez, and colleagues investigated the language detection abilities of eighteen dogs raised in similar settings. The researchers monitored the brain activity of Barney (a golden retriever), Mini (a mixed breed), and other dogs while the animals listened to three recordings: one of The Little Prince being read in Spanish, the second in Hungarian, and a third made up of short, randomly selected fragments of the first two, scrambled so that they didn't resemble human speech. Each dog was familiar with either Spanish or Hungarian, but not both. The team concluded that the amount of previous language exposure a dog has received may influence its ability to distinguish familiar languages from unfamiliar ones.",
          "question": "Which finding from the study, if true, would most directly support the team's conclusion?",
          "options": [
            "Although the dogs' general hearing sensitivity declined with age, dogs of all ages showed more brain activity in response to hearing the language they were accustomed to than in response to hearing the other language.",
            "The difference between the pattern of brain activity a dog showed when hearing the language it was accustomed to and the pattern of brain activity it showed when hearing the language it was not accustomed to was greatest among older dogs.",
            "The similarity between the pattern of brain activity a dog showed in response to hearing the scrambled recording and the pattern of brain activity it showed in response to hearing the language it was not accustomed to was greatest among older dogs.",
            "Dogs showed a different pattern of brain activity when hearing the language they were accustomed to than when hearing the scrambled recording, and the difference in brain activity increased with the age of the dog scanned."
          ],
          "answer": 1
        },
        {
          "id": 14,
          "passage": "Manchester United Football Club won more than half its home matches between 1947 and 2003, helping to distinguish the team as a top British professional soccer club. Additionally, Manchester United, whose home uniform color is mainly red, was more successful in home matches than was Coventry City Football Club, whose home uniform color is not red. Research has shown that many people associate the color red with power and dominance. Past experiences with red objects such as stop signs can even cause people to respond to the color red with caution and hesitation. These findings, if applicable in the context of athletic competitions, could suggest that the uniforms worn by Manchester United's players in their home matches may have __________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "increased Manchester United players' sense of excitement.",
            "negatively affected the performance of players on opposing teams.",
            "led fans to perceive the team's opponents as more dominant than they actually were.",
            "caused Manchester United's players to play less skillfully."
          ],
          "answer": 1
        },
        {
          "id": 15,
          "passage": "Biologists Rebecca M, Calisi-Rodriguez and George E. Bentley examined research on white-throated sparrows and degus, both of which have been studied in the laboratory as well as in the wild, to see how studies' settings might have affected their results. Lab studies are useful because they make it easy to control important variables, but white-throated sparrows' surroundings can significantly affect their hormone levels. Therefore, it's not altogether surprising that when Calisi-Rodriguez and Bentley examined studies of white-throated sparrows, they found that __________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "hormone levels were higher in wild males than in captive male degus.",
            "captive sparrows and wild sparrows usually exhibited very similar hormone levels.",
            "significant differences in hormone levels between individuals were found for both captive sparrows and wild sparrows.",
            "baseline levels of the hormone corticosterone are higher in captive sparrows than they are in wild sparrows."
          ],
          "answer": 3
        },
        {
          "id": 16,
          "passage": "Exclusively inhabiting tropical countries such as Liberia, wild chimpanzees lack adaptations to seasonal variations in ultraviolet B (UVB) irradiance from sunlight; since UVB exposure enables vertebrates to synthesize vitamin D, this raises questions about how chimpanzees in mid-latitude zoos are affected by the lower and more variable UVB irradiance in those locations. In a study of zoo chimpanzees in Norway and other mid-latitude countries, Sophie Moittié and colleagues found not only that chimpanzees' vitamin D levels correlate with UVB irradiance but also that vitamin D levels show no evidence of plateauing as UVB irradiance reaches its highest local levels, suggesting that __________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "averaged across seasons, vitamin D levels in zoo chimpanzees in mid-latitude countries such as Norway tend to be comparable to those in wild chimpanzees in tropical countries such as Liberia.",
            "adaptations to seasonal variations in UVB irradiance may be emerging in zoo chimpanzees in Norway and other mid-latitude countries.",
            "zoo chimpanzees in Norway and other mid-latitude countries tend to synthesize less vitamin D than they are inherently capable of synthesizing.",
            "providing supplemental vitamin D to chimpanzees in zoos in Norway and other mid-latitude countries would likely not be beneficial."
          ],
          "answer": 2
        },
        {
          "id": 17,
          "passage": "As cheesemaking practices spread throughout Europe and Asia during and after the Neolithic, divergent strategies for preserving milk __________ whereas rennet-coagulated cheesemaking became key to milk preservation in Europe and Southwest Asia, acid-heat coagulation methods became common among nomadic herding populations of the northeastern Eurasian steppe.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "emerged and",
            "emerged",
            "emerged,",
            "emerged:"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 18,
          "passage": "The editors of Home Ground: A Guide to the American Landscape turned to the __________ to craft the entry about \"hueco,\" a term referring to a water-retaining depression in a rock face.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "novelist Stephen Graham Jones,",
            "novelist Stephen Graham Jones",
            "novelist, Stephen Graham Jones,",
            "novelist, Stephen Graham Jones"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 19,
          "passage": "Increased gender diversity is revitalizing the field of economics, according to Harvard's Claudia Goldin. The trailblazing accomplishments of Goldin, winner of the 2023 Nobel Prize in Economics for her work on women in the labor force, __________ to the value of scholars of diverse backgrounds in spurring research into previously unexplored, but vitally important, topics.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "attests",
            "attest",
            "has attested",
            "is attesting"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Form, Structure, and Sense-Subject-Verb Agreement"
        },
        {
          "id": 20,
          "passage": "In the late nineteenth and early twentieth centuries, automobiles were commonly referred to as horseless carriages after the older technology they still resembled. Known as the Brass Era, this period in automotive design is remembered for its grandeur and artistry, its vehicles __________ by collectors for their ornate detailing and gleaming brass fittings.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "highly prized",
            "had been highly prized",
            "are highly prized",
            "were highly prized"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 21,
          "passage": "The Organisation for Economic Co-operation and Development (OECD) tracks comparative price list data for its thirty-eight member countries. According to this data, in July 2021, a \"basket\" of goods and services priced at 100 US dollars (USD) in the United States would have cost 105 USD in fellow OECD member __________",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "nation—Finland.",
            "nation: Finland.",
            "nation, Finland.",
            "nation Finland."
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 22,
          "passage": "English poet and Shakespeare contemporary John Donne's __________ much admired during his lifetime (1572-1631) and in the decades that followed, had, at the time of their enthusiastic rediscovery by the early twentieth-century modernists, been essentially gathering dust for the intervening 250 years.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "works,",
            "works, were",
            "works were",
            "works had been"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 23,
          "passage": "Following the American Revolutionary War, North American foodways underwent a radical transformation, fueled in large part by spiking consumer demand for certain grains. The cultivation, trade, and transportation of maize and wheat, __________ reconfigured the continent's existing regional foodways into a globally oriented food system.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "by comparison,",
            "second of all,",
            "alternatively,",
            "in particular,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 24,
          "passage": "With some elements, like phosphorus, scientists were able to isolate a relatively pure sample of the substance shortly after discovering its existence—but this wasn't the case with all elements. __________ the isolation process took a few years. The element molybdenum, for instance, was discovered in 1778 but not isolated until 1781.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "Even so,",
            "Similarly,",
            "Furthermore,",
            "Often,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 25,
          "passage": "Eirene, one of the eighty known moons of Jupiter, is designated as Jupiter LVII (\"LVII\" means \"57\"). Roman numerals typically indicate the order in which the moons were named rather than the order of their proximity to Jupiter. It is incorrect to assume, __________ that Eirene is the fifty-seventh moon from Jupiter in terms of proximity.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "moreover,",
            "finally,",
            "however,",
            "then,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 26,
          "passage": "While researching a topic, a student has taken the following notes: • Ibn Sina was a Persian philosopher and physician. • His book The Canon of Medicine recorded the most advanced medical knowledge of his time. • It was published in the year 1025 CE. • It was used as a medical textbook in Middle Eastern and European universities for centuries.",
          "question": "The student wants to identify the year that The Canon of Medicine was published. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "Ibn Sina recorded the most advanced medical knowledge of his time in his book The Canon of Medicine.",
            "A Persian philosopher and physician wrote a medical textbook called The Canon of Medicine.",
            "The Canon of Medicine was a medical textbook used by Middle Eastern and European universities for centuries.",
            "Ibn Sina's book The Canon of Medicine was published in the year 1025 CE."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes. • There are more than 500 National Wildlife Refuges (NWRs) across the United States. • The Crocodile Lake NWR is a 6,686-acre area in Florida, on the Atlantic coast. • It was established to protect the endangered American crocodile. • The Nestucca Bay NWR is a 457-acre area in Oregon, on the Pacific coast. • It was established to protect the endangered Aleutian Canada goose.",
          "question": "The student wants to provide an overview of the NWR program. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "The US's more than 500 NWRs protect endangered species from coast to coast.",
            "Both the Crocodile Lake NWR and the Nestucca Bay NWR were established to protect endangered species.",
            "Oregon's Nestucca Bay NWR was established to protect the endangered Aleutian Canada goose.",
            "One of more than 500 NWRs in the US, the Crocodile Lake NWR encompasses 6,686 acres in Florida."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    }
  ]
} satisfies MockTestSet
