// Generated from sat-cmp-2024-h8-int-02-module-1.json, sat-cmp-2024-h8-int-02-module-2.json
// Review answers and images before publishing.

import type { MockTestSet } from '../mockTestQuestions'

export const importedMockTest = {
  "id": "sat-cmp-2024-h8-int-02",
  "title": "SAT CMP 2024-H8-INT-02(读写M1只有17题且与INT-04 M1重复)",
  "year": 2024,
  "modules": [
    {
      "name": "Module 1 (Routing)",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "The reception of Hena Khan's book Amina's Song has been very good. Many reviewers, booksellers, and librarians have ________ the book, and it won the Asian/Pacific American Award for Literature.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "attacked",
            "overlooked",
            "recommended",
            "misunderstood"
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 2,
          "passage": "The following text is adapted from Mary Seacole's 1857 autobiography Wonderful Adventures of Mrs. Seacole in Many Lands. That journey across the lsthmus [of Panama], insignificant in distance as it was, was by no means an easy one. It seemed as if nature had determined to throw every conceivable obstacle in the way of those who should seek to join the two great oceans of the world.",
          "question": "As used in the text, what does the word \"conceivable\" most nearly mean?",
          "options": [
            "Possible",
            "Regular",
            "Visible",
            "Basic"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context",
          "underline": [
            "conceivable"
          ]
        },
        {
          "id": 3,
          "passage": "Kelp forests grow underwater along the eastern Pacific Coast. These underwater forests are important to fish and other marine animals. Ocean currents can be powerful and rough, making it difficult for animals to find safe places to hide from predators. The underwater forests slow down the currents. This creates a more ________ environment with calmer waters where animals can take shelter.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "surprising",
            "tranquil",
            "imaginative",
            "dangerous"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "The recently observed gamma ray burst GRB 230307A lasted for 200 seconds, ________ for a burst generated by the merger of neutron stars. Bursts caused by neutron mergers typically last fewer than 2 seconds.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "an incident",
            "a reprieve",
            "a coincidence",
            "an oddity"
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "Pteropods are small swimming snails with thin, delicate calcium carbonate shells. These animals are thought to be especially vulnerable to ocean acidification due to calcium carbonate's susceptibility to dissolution at lower pH values. Victoria L. Peck and colleagues recently found that the periostracum (a protective coating on pteropods' outer shells) prevents this dissolution when intact. Moreover, the team was surprised to discover that even when the periostracum is breached, pteropods can still mitigate damage by rebuilding the inner shell wall.",
          "question": "Which choice best describes the main purpose of the text?",
          "options": [
            "To call for additional research on biological mechanisms that improve pteropod survival rates",
            "To address some of the ways ocean acidification has altered pteropod behavior over time",
            "To discuss a conclusion drawn in a study of calcium carbonate's role in protecting the periostracum of pteropods",
            "To present findings that suggest that a concern about the effects of ocean acidification on pteropod shells may be unwarranted"
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 6,
          "passage": "Tokyo has high pedestrian traffic, but simply replicating a feature of Tokyo associated with walkability—e.g., its high population density—may be insufficient to induce increased walking in other cities. As urbanist Mariela Alfonzo argues, our understanding of individuals' decision-making about whether to walk is insufficiently robust: some studies emphasize the role of personal preference, others the role of perceived safety, and so on, but walking decisions are made in complex contexts in which multiple conditions and needs inform individuals' choices.",
          "question": "Which choice best states the main purpose of the text?",
          "options": [
            "To describe the effect of high population density on any given city's walkability",
            "To present a claim about how individuals' decision-making about walking can be improved",
            "To discuss the difficulty of identifying a reliable way to increase walking in any given city",
            "To explain why it is challenging to compare the amount of pedestrian traffic in different cities"
          ],
          "answer": 2,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 9,
          "passage": "The following text is from William Shakespeare's play The Tempest, first performed in 1611. Miranda has lived on an island with her father, Prospero, since she was three years old. Prospero has stated that Miranda likely does not remember anything other than her life on the island. MIRANDA: \"Tis far off, And rather like a dream than an assurance That my remembrance warrants. Had I not Four or five women once that tended me? PROSPERO: Thou hadst, and more, Miranda. But how is it That this lives in thy mind? What seest thou else In the dark backward and abysm of time? If thou remember'st ought ere thou camest here, How thou camest here thou mayst.",
          "question": "In the text, which point does Prospero most directly make about Miranda and her memories?",
          "options": [
            "Miranda's impression of a scene is vague because she is remembering a scenario she had daydreamed about as a child rather than a scenario that had occurred in reality.",
            "Miranda's doubts about the accuracy of one recollection of a place other than the island are clouding her judgment and seem to be making her reluctant to explore her recollection of traveling to the island.",
            "Miranda's reminiscences about her early childhood have a melancholy quality that betrays her discontented view of her current circumstances.",
            "Miranda's ability to summon details of an experience she had before arriving on the island suggests that she may also be able to summon details of her arrival on the island."
          ],
          "answer": 3
        },
        {
          "id": 10,
          "passage": "The Muscogee Nation and the nearly forty other tribes in Oklahoma operate numerous businesses and collectively generate billions of dollars in revenue, Mining, including oil and natural gas production, is a key industry in the state as well. While researching other key industries in Oklahoma for an economics class, a student finds that the average amount contributed to the state's economy in 2017 by each individual employed in wholesale trade was ________",
          "question": "Which choice most effectively uses data from the table to complete the statement?",
          "options": [
            "$141,510.",
            "$183,790.",
            "$150,373.",
            "$77,247."
          ],
          "answer": 1,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Impact of Four Key Industries on Oklahoma Economy in 2017",
            "headers": [
              "Industry",
              "Approximate total contribution by industry",
              "Number of people employed by industry",
              "Average contribution per employee by industry"
            ],
            "rows": [
              [
                "Accommodation/food services",
                "$5,242,100,000",
                "150,373",
                "$34,861"
              ],
              [
                "Tribal economic activity",
                "$7,312,400,000",
                "51,674",
                "$141,510"
              ],
              [
                "Construction",
                "$6,797,300,000",
                "77,247",
                "$87,994"
              ],
              [
                "Wholesale trade",
                "$10,723,400,000",
                "58,346",
                "$183,790"
              ]
            ]
          }
        },
        {
          "id": 12,
          "passage": "In a college course on urban affairs, a student asserts that increased traffic congestion in the United States in the 1990s was present both in very large cities such as New York City, New York, and smaller areas such as Albany-Schenectady-Troy, New York, and Beaumont, Texas; though those smaller areas may have been less affected by traffic congestion than very large cities, this congestion also worsened in them over time.",
          "question": "Which choice best describes data from the graph that support the student's claim?",
          "options": [
            "In at least one of the three urban areas shown, the amount of traffic delay was less than 20 hours per commuter per year at one point between 1990 and 2000.",
            "In 1992, the amount of traffic delay in the New York City, New York, area was less than 30 hours per commuter per year.",
            "While the annual number of hours of traffic delay per commuter was always lower in the Albany-Schenectady-Troy, New York, area than in the New York City, New York, area for each year between 1990 and 2000, the amount of traffic delay rose in both areas during this period.",
            "Even though the amount of traffic delay per commuter per year was greater in the Albany-Schenectady-Troy, New York, area than in the New York City, New York, area throughout the period from 1990 to 2000, the amounts were nearly identical in 1996."
          ],
          "answer": 2,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "image": "/sat-cmp-2024-h8-int-02-m1-q12.svg"
        },
        {
          "id": 13,
          "passage": "Past research suggests that pollination by honeybees is responsible for up to 10 percent of total onion crop production. Now researchers are trying to determine how dependent cucumber crop production is on honeybees. The first phase of their study involved shielding some cucumber plants to prevent insects from pollinating them, resulting in those plants having 40 to 90 percent lower crop production than plants that were pollinated normally. However, the researchers claim that the first-phase experiment alone didn't tell them how much of that difference in crop production is due specifically to excluding honeybees.",
          "question": "Which finding, if true, would most directly support the researchers' claim?",
          "options": [
            "Other insects like solitary bees also pollinate onion plants, and some studies have allowed them to pollinate normally while excluding honeybees.",
            "Other insects like squash bees also pollinate cucumber plants, and the shielding in the first phase of the study blocked them as well.",
            "Honeybees are more commonly used to pollinate cucumber plants than onion plants.",
            "The shielding used in the first phase of the study did not affect the amount of sunlight the cucumber plants received."
          ],
          "answer": 1
        },
        {
          "id": 15,
          "passage": "In 1988, Arizona ________ official fossil: the Araucarioxylon arizonicum, which is a Triassic period tree.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "lawmakers designated the states",
            "lawmakers designated the state's",
            "lawmaker's designated the state's",
            "lawmaker's designated the states"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 16,
          "passage": "Often anthologized alongside the ________ associated with the Black Arts movement—such as Gwendolyn Brooks and Jayne Cortez—bell hooks's poem \"Appalachian Elegy (Sections 1-6)\" stands out for its memorable last lines: \"the covenant / between us / can never be broken / vows to live and let live.\"",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "work's of other writer's",
            "works of other writers",
            "work's of other writers",
            "works of other writer's"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 17,
          "passage": "The part of a compound that determines the compound's color is ________ the chromophore. One example of a chromophore is hemoglobin, which gives human blood its red color.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "called—",
            "called;",
            "called,",
            "called"
          ],
          "answer": 3,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 18,
          "passage": "Released in 1996, the AMD K5 microchip contained a single CPU, or core, to execute commands. Since then, the average processing power of microchips has increased so drastically—cores now number in the dozens, hundreds, or even ________ the once-revolutionary dual-core technology that replaced the single-core chip can be found in everyday items like toasters and toothbrushes.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "thousands, that",
            "thousands that—",
            "thousands—that",
            "thousands. That"
          ],
          "answer": 2,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 20,
          "passage": "When a given industry—water and electricity are two well-known examples—carries high infrastructural start-up costs and other barriers that discourage competition, ________ of just one or two suppliers per municipality. Such industries are known as natural monopolies.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "it often consists",
            "they often consist",
            "these often consist",
            "this often consists"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Sentence Completeness"
        },
        {
          "id": 26,
          "passage": "• Jean-Michel Basquiat was an American artist who produced more than two thousand drawings and paintings. • His work Untitled (Prophet I) was completed in 1982 and sold at auction in 2011. • Untitled (Prophet I) is composed of acrylic, oil stick, and paper collage on canvas and measures 5,655 square inches in area. • His work Catharsis was completed in 1983 and sold at auction in 2008. • Catharsis is composed of acrylic and oil stick on canvas and measures 6,750 square inches in area.",
          "question": "Which choice most effectively uses information from the given sentences to emphasize how the two works are similar?",
          "options": [
            "Composed by artist Jean-Michel Basquiat in 1982 and 1983, respectively, both Untitled (Prophet l) and Catharsis use acrylic paint as a medium.",
            "Artist Jean-Michel Basquiat completed Untitled (Prophet I) in 1982, and Catharsis followed in 1983.",
            "Artist Jean-Michel Basquiat's work Untitled (Prophet I) is composed of acrylic, oil stick, and paper collage, while Catharsis is composed of acrylic and oil stick.",
            "Between artist Jean-Michel Basquiat's works Catharsis and Untitled (Prophet I), the former is the larger of the two."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes: • Onomatopoeias are words that imitate the sounds they represent. • Words that represent the same sound are often written and pronounced very differently from language to language • This variation is due in part to differences in how the languages are structured. • \"Khrok fi\" is a Thai onomatopoeia that represents the sound of snoring. • \"Bhnosh\" is a Bengali onomatopoeia that represents the sound of snoring.",
          "question": "The student wants to contrast two words that represent the same sound. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "The Thai word \"khrok fi\" and the Bengali word \"bhnosh\" are onomatopoeias that represent the sound of snoring.",
            "Though they both represent the sound of snoring, the onomatopoeias \"khrok fi\" (Thai) and \"bhnosh\" (Bengali) are written and pronounced very differently.",
            "Onomatopoeias, words that imitate the sounds they represent, are often written and pronounced very differently from language to language.",
            "The Thai word \"khrok fi,\" which represents the sound of snoring, is an onomatopoeia."
          ],
          "answer": 1,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    },
    {
      "name": "Module 2",
      "subject": "阅读与文法",
      "timeMinutes": 32,
      "questions": [
        {
          "id": 1,
          "passage": "Smartphones and other small electronic devices tend to use batteries that can't be easily taken out and swapped for new ones. Environmental policy researcher Jean-Pierre Schweitzer warns that when these internal batteries stop working, the devices are usually thrown away, becoming harmful ________.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "advice",
            "waste",
            "rewards",
            "positions"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 2,
          "passage": "The following text is adapted from Kenneth Grahame's 1908 novel The Wind in the Willows. The Mole has been found by a friend after getting lost in the woods, It is beginning to snow. The Mole saw the wood that had been so dreadful to him in quite a changed aspect. Holes, hollows, pools, pitfalls, and other menaces to the wayfarer were vanishing fast, and a gleaming carpet was springing up everywhere, that looked too delicate to be trodden upon by rough feet.",
          "question": "As used in the text, what does the word \"delicate\" most nearly mean?",
          "options": [
            "Generous",
            "Fragile",
            "Accurate",
            "Empty"
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Words in Context",
          "underline": [
            "delicate"
          ]
        },
        {
          "id": 3,
          "passage": "Jean Batten, who was the first person to fly between England and New Zealand solo, and Ynes Mexia, who was the first to discover the botanical genus Mexianthus, are ensured lasting places in our historical memory. No matter what others may do in the future, nobody can ever ________ the standing of these women as the first to accomplish these feats.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "undermine",
            "imply",
            "extend",
            "promote"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 4,
          "passage": "Whatever the general attitude toward Madeline Anderson's 1970 film I Am Somebody and Reginald Hudlin's 1990 film House Party when they were initially released, both films now tend to be regarded quite ________. In 2018, for example, critics for the New York Times praised the former as \"galvanizing\" and the latter as \"exuberant.\"",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "favorably",
            "skeptically",
            "neutrally",
            "strangely"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 5,
          "passage": "To evaluate their ideas about environmental conditions in the Pliocene epoch, paleontologists must turn to ________ evidence. Only material objects—such as the fossil remains of the individual known as AL 200-1, discovered in Ethiopia in 1975—can show whether a particular idea about the Pliocene is defensible.",
          "question": "Which choice completes the text with the most logical and precise word or phrase?",
          "options": [
            "physical",
            "convenient",
            "creative",
            "inconclusive"
          ],
          "answer": 0,
          "domain": "Craft and Structure",
          "skill": "Words in Context"
        },
        {
          "id": 6,
          "passage": "Joseph A. Walker's award-winning play The River Niger was produced in 1972 by the groundbreaking Negro Ensemble Company (NEC). NEC cofounder Douglas Turner Ward, who worked as an actor, director, and playwright, had met actor and producer Robert Hooks while they were performing in a 1960 touring production of Lorraine Hansberry's play A Raisin in the Sun. Together, they envisioned a theater company that would nurture and showcase the work of Black theater professionals. Since NEC's founding in 1967, its workshops and performances have given Black playwrights, including Walker, a forum for their compelling stories.",
          "question": "Which choice best describes the function of the underlined portion in the text as a whole?",
          "options": [
            "It illustrates the importance of an organization mentioned in the text.",
            "It compares the achievements of two people discussed later in the text.",
            "It argues against the claim made earlier in the text.",
            "It provides additional information about a person discussed in the text."
          ],
          "answer": 3,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 7,
          "passage": "Burt Kotler and colleagues showed that high moonlight intensity inhibits the activity of the greater Egyptian gerbil (Gerbillus pyramidum), a finding explicable in terms of benefits and costs: greater lunar intensity may not enable the gerbils to increase foraging success enough to offset the higher chance of detection by predatory foxes or owls. Though many other nocturnal mammals respond to lunar intensity variations similarly to greater Egyptian gerbils, Mohol bushbabies (Galago moholi) display the opposite pattern, as their heavy reliance on visual foraging results in a different balance of reward and risk.",
          "question": "Which choice best describes the function of the reference to \"heavy reliance on visual foraging\" in the text as a whole?",
          "options": [
            "It emphasizes an attribute of Mohol bushbabies that enables them to respond to lunar intensity variations more rapidly than greater Egyptian gerbils and many other nocturnal mammals do.",
            "It identifies a characteristic of Mohol bushbabies that explains why they do not reduce their activity under high lunar intensity like greater Egyptian gerbils and many other nocturnal mammals do.",
            "It describes a behavioral pattern displayed by Mohol bushbabies that is inconsistent with how they would be expected to respond to high lunar intensity based on benefits and costs.",
            "It presents a trait of Mohol bushbabies that serves as evidence for the assertion that greater Egyptian gerbils are not the only nocturnal mammals whose activity is inhibited by high lunar intensity."
          ],
          "answer": 1,
          "domain": "Craft and Structure",
          "skill": "Text Structure and Purpose"
        },
        {
          "id": 8,
          "passage": "Text 1 Isaac Asimov, author of The Caves of Steel and The Stars, Like Dust, is highly regarded despite his mediocre writing style. His prose is workmanlike; his characters are flat and discuss ideas rather than emotions. That his work is enjoyable despite this is a testament to his prodigious imagination—even if people read his books only for the ideas, they will have plenty to consider. Text 2 Asimov is critiqued for his style, but it is wrong to fault a writer for failing to do what he never intended to do. For example, although most of his novel Foundation consists of people discussing science and politics and we find out little about his characters' lives, Asimov wanted to convey the vast sweep of human history over centuries, and one of his points is that at such a timescale, individuals don't matter. Thus his lack of characterization is central to his thematic aims.",
          "question": "Based on the texts, how would the author of Text 2 most likely respond to the description of Asimov's characters in the underlined portion of Text 1?",
          "options": [
            "Asimov's characterizations would have been richer if he had possessed a deeper understanding of history.",
            "The flatness of Asimov's characters is a feature of The Caves of Steel and The Stars, Like Dust but not of Foundation.",
            "The flatness of Asimov's characters should not necessarily be considered a flaw in his writing.",
            "Asimov's characterizations would have been more believable if his writing had discussed fewer ideas."
          ],
          "answer": 2
        },
        {
          "id": 9,
          "passage": "Animals use many objects as tools to achieve goals more easily. Such goals include grooming, finding food, and protecting themselves. For a long time, people thought tool use was unique to primates. Sea otters and other animals, though, have busted the myth that tool use is limited to certain primates. Inventively, sea otters use stationary anvil stones to break open mollusk shells. Woodpecker finches also get creative. They use cactus spines to pry insects from hiding places.",
          "question": "Which choice best states the main idea of the text?",
          "options": [
            "Animals find it difficult to use objects as tools.",
            "Unlike primates, sea otters are exceptionally skillful at using different tools.",
            "Contrary to long-held beliefs, primates aren't the only animals to use tools.",
            "There are many myths about tool use that researchers are starting to challenge."
          ],
          "answer": 2
        },
        {
          "id": 10,
          "passage": "A student is writing a paper on the global rise of the home video game industry during the 1980s. The student wants to know the release year of the video game Zelda II: The Adventure of Link, developed by Nintendo EAD. The student finds that this game was released in _________",
          "question": "Which choice most effectively uses data from the table to complete the statement?",
          "options": [
            "1982.",
            "1987.",
            "1984.",
            "1988."
          ],
          "answer": 1,
          "domain": "Information and Ideas",
          "skill": "Command of Evidence-Quantitative Evidence",
          "table": {
            "title": "Home Video Games and Computer Games of the 1980s",
            "headers": [
              "Title",
              "Approximate number of units sold worldwide",
              "Release year",
              "Genre",
              "Developer"
            ],
            "rows": [
              [
                "Excitebike",
                "4,160,000",
                "1984",
                "racing",
                "Nintendo R&D1"
              ],
              [
                "The Last Ninja 2",
                "5,500,000",
                "1988",
                "action-adventure",
                "System 3"
              ],
              [
                "Zelda II: The Adventure of Link",
                "4,380,000",
                "1987",
                "action-adventure",
                "Nintendo EAD"
              ],
              [
                "Frogger",
                "4,100,000",
                "1982",
                "action",
                "Konami"
              ]
            ]
          }
        },
        {
          "id": 11,
          "passage": "A film studies student is researching early 20th-century film serials, which consisted of individual episodes of a single long story that were shown weekly in theaters. Clancy of the Mounted is a 1933 serial that, over its 12 episodes, kept its audience interested with the suspense and drama that are typical of the northern adventure genre. The student, however, claims that ultimately audiences of the time preferred resolution and closure over ongoing tension.",
          "question": "Which finding, if true, would most directly support the student's claim?",
          "options": [
            "The 12th episode of Clancy of the Mounted was the most expensive episode of the series to produce.",
            "The 12th episode of Clancy of the Mounted was viewed by more people than was any previous episode in the series.",
            "Modern critics generally regard the first episode as the best installment of Clancy of the Mounted.",
            "Audiences of the time considered Clancy of the Mounted to belong to a genre other than the northern adventure genre."
          ],
          "answer": 1
        },
        {
          "id": 12,
          "passage": "Treasure Island is an 1883 novel by Robert Louis Stevenson. When the narrator was a child, his father ran a hotel. A mysterious sailor came to stay at the hotel. The narrator was frightened of the sailor, as can be seen when the narrator says, ________",
          "question": "Which quotation from Treasure Island most effectively illustrates the claim?",
          "options": [
            "\"How [the sailor] haunted my dreams, I need scarcely tell you. On stormy nights, when the wind shook the four corners of the house and the surf roared along the cove and up the cliffs, I would see him in a thousand forms, and with a thousand diabolical expressions.\"",
            "\"I remember [the sailor] as if it were yesterday, as he came plodding to the inn door, his sea-chest following behind him in a hand-barrow.\"",
            "\"[The sailor] was a very silent man by custom. All day he hung round the cove or upon the cliffs with a brass telescope.\"",
            "\"All the time he lived with us [the sailor] made no change whatever in his dress but to buy some stockings from a hawker, One of the [corners] of his hat having fallen down, he let it hang from that day forth, though it was a great annoyance when it blew.\""
          ],
          "answer": 0
        },
        {
          "id": 13,
          "passage": "Students in a biology class investigated why individual house mice (Mus musculus) can differ from one another in their susceptibility to cataracts in old age. The students compared wild-type mice and knockout mice, which are mice with specific genes deactivated, when mice of each type were raised in similar naturalistic environments and periodically tested for cataracts. Finding that knockout mice with the gene Aasdh deactivated tended to develop cataracts more frequently than did wild-type mice, the students concluded that differences in cataract frequency among house mice in nature are solely attributable to variations in the level of expression of Aasdh.",
          "question": "Which finding, if true, would most directly weaken the students' conclusion?",
          "options": [
            "Some wild-type mice were very similar to the knockout mice with regard to cataract frequency but showed a wide variety of levels of expression of Aasdh.",
            "The level of expression of Aasdh does not appear to affect the functioning of any other genes in house mice.",
            "A sampling of house mice captured in natural settings shows that individual mice can differ from one another in the level of expression of Aasdh.",
            "The mice with Aasdh deactivated were identical to the wild-type mice except with regard to cataract frequency."
          ],
          "answer": 0
        },
        {
          "id": 14,
          "passage": "Narwhals are shy whales that live in the remote Arctic Ocean. Some of them have a long tusk, like a unicorn horn, with sensitive nerves. Narwhals are known for this tusk, but many actually don't have one and its purpose is unknown. One group of scientists came up with a possible purpose in 2014. The scientists suggested that the tusk may help narwhals determine when water around them is likely to start freezing and become dangerous for them. Marine biologist Kristin Laidre disagrees with that idea, though. She reasons that if the narwhal's tusk serves such an important purpose, then it's most likely that ________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "some narwhals would seek a new habitat.",
            "more narwhals would have a tusk.",
            "fewer marine animals would also have tusks.",
            "narwhals would become less shy over time."
          ],
          "answer": 1
        },
        {
          "id": 15,
          "passage": "Over 600 languages are spoken in New York City in addition to English—one can find Bartangi spoken in the neighborhood of Yorkville, or Ghale in Jackson Heights. Most speakers of Chinese languages reside in the neighborhood of Flushing (part of New York City's borough of Queens) and in Chinatown, in the borough of Manhattan. New immigrants from north China, where Mandarin is the primary first language, tend to settle in Queens, while new immigrants from south China, where many people speak Cantonese or Fuzhounese as a first language, tend to settle in Manhattan. It can therefore be inferred that ________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "languages tend to change more rapidly in areas where many languages are spoken than in areas where few languages are spoken.",
            "correlations in a country between languages and regions where they are spoken can replicate themselves in a new country to which the original country's citizens emigrate.",
            "languages spoken by immigrant peoples can differ significantly in vocabulary and pronunciation from those same languages in their country of origin.",
            "there is a positive correlation between the physical size of a country and the number of languages spoken in that country."
          ],
          "answer": 1
        },
        {
          "id": 16,
          "passage": "F. Scott Fitzgerald's 1920 novel This Side of Paradise contains elements drawn from Fitzgerald's own life—there are many parallels between the experiences of the novel's protagonist, Amory Blaine, and those of Fitzgerald—and as a result This Side of Paradise is regularly described as an autobiographical novel. This characterization can be useful, but it also presents drawbacks in terms of how the work is perceived, as it may lead readers to believe that Fitzgerald merely fictionalized true events, which, in an artistic field where creativity and inventiveness are prized, can suggest that ________",
          "question": "Which choice most logically completes the text?",
          "options": [
            "This Side of Paradise is less of an imaginative achievement than it actually is.",
            "Fitzgerald should not have claimed that This Side of Paradise is based on real events.",
            "critics disagree about whether This Side of Paradise shows greater originality than works without autobiographical elements.",
            "the real-world counterparts of other characters in This Side of Paradise are hard to identify."
          ],
          "answer": 0
        },
        {
          "id": 17,
          "passage": "Completed in 1886, Vincent van Gogh's drawing Behind the Hedge is less well known than his ________ it is still considered by scholars to be an important work.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "paintings, but",
            "paintings,",
            "paintings",
            "paintings but"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 18,
          "passage": "On the other hand, Kansas City International Airport, which ________ located in Kansas City, Missouri, saw an overall increase in departing passengers over the same time period, from 4,891,704 total passengers to 5,759,138.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "is",
            "are",
            "were",
            "have been"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Form, Structure, and Sense-Subject-Verb Agreement"
        },
        {
          "id": 19,
          "passage": "When Anglo and African Americans moved West in the nineteenth century to begin cattle ranching, they learned the trade from Spanish-speaking Mexican vaqueros (cowboys). This is why many ranching terms come from ________ English word \"lasso\" (a rope) comes from the Spanish word lazo, and \"cinch\" (a belt) comes from cincho.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "Spanish. The",
            "Spanish (the",
            "Spanish the",
            "Spanish? The"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Punctuation"
        },
        {
          "id": 20,
          "passage": "The fact that many even-toed ungulates, including the Bawean deer (Axis kuhlii) and the south Andean deer (Hippocamelus bisulcus), meet the population criteria for endangered status validates the need for interventions that can prevent ________ from joining the ranks of the extinct.",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "the animal",
            "these animals",
            "this animal's",
            "these animals'"
          ],
          "answer": 1,
          "domain": "Standard English Conventions",
          "skill": "Boundaries-Possessive Nouns and Plural Forms"
        },
        {
          "id": 21,
          "passage": "Water boils at around 212°F at sea level, but in Questa, New Mexico (elevation: 7,461 feet above sea level), it boils at around 198°F. Food writer J, Kenji López-Alt, who explores the science behind cooking, ________ that lower boiling points at higher elevations \"can wreak all sorts of havoc on recipes.\"",
          "question": "Which choice completes the text so that it conforms to the conventions of Standard English?",
          "options": [
            "explains",
            "are explaining",
            "explain",
            "have explained"
          ],
          "answer": 0,
          "domain": "Standard English Conventions",
          "skill": "Form, Structure, and Sense-Subject-Verb Agreement"
        },
        {
          "id": 22,
          "passage": "While not the case with dimples, some inherited observable traits, or phenotypes, can change because of a variety of factors. ________ eye color can change because of age.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "For example,",
            "Finally,",
            "Conversely,",
            "In any case,"
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 23,
          "passage": "Just as the state of New York has a designated state flower, tree, and bird, it also has a state soil: Honeoye soil. Honeoye is a fitting choice for state soil, in large part because it can be found in abundance across the state. ________ it plays an important role in New York's agricultural industry and is used to grow a variety of crops, like corn and soybeans.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "At that time,",
            "Alternatively,",
            "Conversely,",
            "Moreover,"
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 24,
          "passage": "Roughly once an hour, a torrent of boiling water shoots up 100 feet or more from Yellowstone's Old Faithful geyser before plunging back to the surface—a cycle seemingly inhospitable to life. ________ as microbiologist Eric Boyd attests, \"the geyser is...almost like a cradle for biodiversity,\" home to numerous bacteria species that thrive in its sulfurous waters.",
          "question": "Which choice completes the text with the most logical transition?",
          "options": [
            "Thus,",
            "Still,",
            "Specifically,",
            "In other words,"
          ],
          "answer": 1,
          "domain": "Expression of Ideas",
          "skill": "Transitions-Logical Transition Words and Phrases"
        },
        {
          "id": 25,
          "passage": "• Impact craters occur when a large object collides with Earth at high speeds. • Examples of such objects include comets and meteorites. • Newporte is an impact crater in the United States. • Researchers have determined that it was formed less than 500 million years ago. • The crater has a diameter of approximately 3.2 km.",
          "question": "Which choice most effectively uses information from the given sentences to emphasize the size of the crater?",
          "options": [
            "Long ago, a crater now known as Newporte was created when a large object collided with Earth.",
            "Impact craters, like Newporte in the United States, are formed when a massive object collides with Earth, creating depressions in the land.",
            "Researchers have investigated the formation of Newporte, an ancient impact crater measuring 3.2 km in diameter located in the United States.",
            "When a large object struck what is now the United States less than 500 million years ago, it created Newporte, a massive crater measuring 3.2 km in diameter."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 26,
          "passage": "While researching a topic, a student has taken the following notes: • \"Raymond's Run\" is a short story. • It was written by African American author Toni Cade Bambara. • It was first published in her book Gorilla, My Love in 1972. • It is told from a first person perspective. • It takes place in Harlem.",
          "question": "The student wants to indicate where the short story takes place. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "\"Raymond's Run\" takes place in Harlem.",
            "\"Raymond's Run\" was written by Toni Cade Bambara.",
            "\"Raymond's Run\" was published in Gorilla, My Love.",
            "\"Raymond's Run\" is told from a first person perspective."
          ],
          "answer": 0,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        },
        {
          "id": 27,
          "passage": "While researching a topic, a student has taken the following notes: • The green iguana is a species of reptile. • It can be found in Central America and Brazil. • The green iguana primarily eats leaves and fruit. • It has an average length of 4.8 feet.",
          "question": "The student wants to specify the average length of the green iguana. Which choice most effectively uses relevant information from the notes to accomplish this goal?",
          "options": [
            "The green iguana is a reptile that primarily eats leaves and fruit.",
            "One species of reptile found in Brazil primarily eats leaves and fruit.",
            "The green iguana can be found in Central America.",
            "The green iguana has an average length of 4.8 feet."
          ],
          "answer": 3,
          "domain": "Expression of Ideas",
          "skill": "Rhetorical Synthesis-Logical Combination of Information"
        }
      ]
    }
  ]
} satisfies MockTestSet
